### ISSUE TITLE
Fails to safe proprerly

### ISSUE THREAD

**Issue by dvdobrovolskiy** [SchoofsKelvin/vscode-sshfs#10]
Just cuts half a file when saving. 

setInterval(function() {
         console.log( "tick!" );
    }, 2000);   

becomes
setInterval(function() {
         conso

**Comment by SchoofsKelvin** [comment]
I haven't had that happen before. Does it happen every time? Are you using UTF-8 or another character encoding?

**Comment by dvdobrovolskiy** [comment]
UTF-8
Not often. 2 happened time I think.

**Comment by SchoofsKelvin** [comment]
I've recently improved the SSHFileSystem class, making it wait with calling SSH2Stream methods when needed. As the .write methods don't have this system, I'm not entirely sure if this is fixed.

If this happens again, I'll reopen the issue.
