### ISSUE TITLE
Mount point in local file system

### ISSUE THREAD

**Issue by tanc** [SchoofsKelvin/vscode-sshfs#103]
I'm currently trying a particularly mind bending xdebug set up with VSCode where I have a server (local network) which runs a set of Docker containers, inside of which PHP and xdebug (with Apache serving) are running. On my laptop I'm viewing the site in my browser and triggering xdebug inside the containers. Also on my laptop I have mounted the server's files through this extension (sshfs).

This is almost working for me but I'm having trouble mapping the file paths. When xdebug triggers on an error I'm seeing file not found messages like this:

![screenshot of problem](https://cl.ly/d03dafabcbbe/Image%202019-02-11%20at%209.15.28%20am.png)

Where does this extension mount the workspace on the local machine?

Currently my debug config for path mapping is:

```
      "pathMappings": {
        "/app/web": "${workspaceRoot}/web"
      }
```
This should be correctly mapping the path within the container (where xdebug is running) to the workspace but isn't working as shown in the screenshot above.

Maybe I need to be more explicit in my path mapping for the local part? Instead of `${workspaceRoot}` use the full path to the mount point for example.

**Comment by tanc** [comment]
I've just tried to specify `ssh://` like:
```
      "pathMappings": {
        "/app/web": "ssh://iucnflr/web"
      }
```
But this results in `file://` being prepended:

![screenshot showing file:// prepended](https://cl.ly/6c2a68af04c7/Image%202019-02-11%20at%209.34.23%20am.png)

**Comment by SchoofsKelvin** [comment]
The extension doesn't mound the workspace anywhere on the local machine. All files/directories are saved/read over the SSH connection. VSCode keeps track of which files are open, caching directory entries, ... it only asks the extension to read/write directories/files.

Lots of extensions don't support non-local file systems right now. See #42 for more information.

**Comment by tanc** [comment]
Thank you, I had a feeling it would be the extensions problem. Will open an issue with them

**Comment by SchoofsKelvin** [comment]
VSCode currently doesn't provide an API to extensions for this, so as far as I know, they can't solve the issue right now. (Microsoft/vscode#48034)
