### ISSUE TITLE
How do I set it for a public key?

### ISSUE THREAD

**Issue by Thrush911** [SchoofsKelvin/vscode-sshfs#108]
How do I set it for a public key?

I made the settings as below.
`"privateKeyPath": "/home/user/.ssh/xxx.pub",`
` "passphrase": false`

But, I got a error message, `Error while connecting to SSH FS sample: Error while reading the keyfile at: /home/user/.ssh/xxx.pub`.

**Comment by rosterloh** [comment]
Same issue. Whats the procedure for connecting with a key and no password?

**Comment by SchoofsKelvin** [comment]
If the private key doesn't require a passphrase, leaving the passphrase empty (or not having it in the config) should work.

As for host-based authentication, I know barely anything about it, but the [ssh library](https://www.npmjs.com/package/ssh2#client-methods) I use apparently supports it, with it just using the `privateKey` or `privateKeyPath` fields.

Based on that error, it's actually reading the file that went wrong. Make sure the path is correct, and that the permissions make it readable for the user vscode runs as.

**Comment by SchoofsKelvin** [comment]
I assume this issue is solved
