### ISSUE TITLE
Can't save/edit/create files

### ISSUE THREAD

**Issue by Vslira** [SchoofsKelvin/vscode-sshfs#109]
First of all, thanks @SchoofsKelvin for the extension!

So, apparently I'm having a problem no one else does: I can connect to the remote directory, see and download all the files just fine. I just can't save changes or create files. The only error message I get is

> **[Failed to create]** ssh://folder_name/file

when creating a file and

> **[Failed to save 'file': Permission denied]**

Setup: MacOS High Sierra, VSCode version 1.31.1

This happens when logging into the remote server both as a user or as root

Does anyone have any idea of what could be the problem?

Thanks!

**Comment by SchoofsKelvin** [comment]
Could you give me a concrete path for the file, along with the output of `ls -lah` in its parent directory? While permission being denied for regular users isn't that strange, it being denied for root is a bit unusual. The permissions for the file/directory might actually be set to restrict writing for everyone, though.

**Comment by Vslira** [comment]
@SchoofsKelvin Well this is awkward but unfortunately I can't provide the full path (containing names of clients, etc). I can create/edit files just fine when ssh'ing to that machine.

I'll try to find out what's wrong/how to fix and post here if I do. Thanks for the attention :)

**Comment by alcalyn** [comment]
I have the same problem.

I connected with ssh, using my host, user, set password to `<prompt>`.

I can successfully browse my files, but getting Denied access when trying to edit or create file.

**Comment by elelement** [comment]
Hello. I'm facing a similar issue, if not the same. I can edit files when logged in via terminal, but not through the plugin.
This is what I'm trying to edit:
```
$ ls -lah rules/
total 24K
drwxr-xr-x  2 openhab openhab 4,0K ago 24 16:31 .
drwxr-xr-x 13 openhab openhab 4,0K may 18  2018 ..
-rw-rw-r--  1 openhab openhab 1,4K ago 25 11:46 device_4.rules
-rw-rw-r--  1 openhab openhab 1,5K ago 22 11:01 device_5.rules
-rw-rw-r--  1 openhab openhab 1,5K ago 22 10:08 device_6.rules
-rw-r--r--  1 openhab openhab  223 jun 22 14:15 readme.txt
```

I'm logging in as **"pi"** user and it belongs to the "openhab" group:
`sudo adduser pi openhab`

**Using vim or nano as "pi" allows me to edit the files** (iTerm terminal), but the plugin doesn't. Even if I use the option "open a remote SSH terminal" it doesn't work:

- Using plugin's VS Code editor:
`Failed to save 'device_4.rules': Unable to write file 'ssh://openhab-config/rules/device_4.rules' (NoPermissions (FileSystemError): ssh://openhab-config/rules/device_4.rules)`
- Using plugin's terminal option and then, using vim:
`E45: La opción 'readonly' está activada (añada "!" para forzar)  `
In the VS Code console I can see that the plugin logs in as "pi" user:
`pi@raspberrypi:/etc/openhab2$  `

There has to be something wrong with plugin. How can I enable some kind of debug log?

Thank you very much.

**Comment by elelement** [comment]
Well, what I see is that you can only edit files belonging specifically to the user you configured to log in. In a normal ssh connection, through iTerminal, for example, I am able to edit files using group permissions. In other words, if the user "pi" belongs to group openhab, I'll be able to edit files belonging to that group, even if "pi" is not the propietary (664 permissions, for example).
It seems to me, that this plugin is only checking that the file owner is equal to the logged in user.

Could we reopene this issue? Thank you very much.
