### ISSUE TITLE
Using SSH_AUTH_SOCK as agent

### ISSUE THREAD

**Issue by aigan** [SchoofsKelvin/vscode-sshfs#11]
How do I use the existing ssh setup without having to enter a password?

The docs says to enter the Path to ssh-agent's UNIX socket. But that path could change. It's in the SSH_AUTH_SOCK environment variable. How do I get the extension to use that path?

**Comment by SchoofsKelvin** [comment]
I'll see if I can substitute environment variables from some options, like the agent path. Using `"agent": "$SSH_AUTH_SOCK"` should then work.

**Comment by SchoofsKelvin** [comment]
Support for environment variables added in ee40dcb (published in 1.6.0)
