### ISSUE TITLE
Missing property "privateKey"

### ISSUE THREAD

**Issue by jribbens** [SchoofsKelvin/vscode-sshfs#111]
I think it's worth having an open ticket on the fact that sshfs complains `Missing property "privateKey"` if you set up a config with a `privateKeyPath` and no `privateKey`, and `Matches a schema that is not allowed` if you add an empty `privateKey` to try and silence the first problem.

**Comment by siaarzh** [comment]
I just removed a the following line (and the `,` before it) in my `%HOMEPATH%/.vscode/extensions/kelvin.vscode-sshfs-1.13.0/package.json` for now, because that warning is annoying af.

https://github.com/SchoofsKelvin/vscode-sshfs/blob/bb7702ee0cfef5c5514d5c7193fd906525ecfe31/package.json#L281

**Comment by SchoofsKelvin** [comment]
I've removed the JSON validation (f2da110d), since the recommended way of editing configurations is by using the Settings UI. Some options (e.g. proxies) aren't supported by the UI yet, but I'll add support for that soon.
