### ISSUE TITLE
Can't connect trough proxy (HowTo for Dummies req)

### ISSUE THREAD

**Issue by ThomasSiemens** [SchoofsKelvin/vscode-sshfs#112]
I've searched through all the open and resolved issues regarding this but I'm can't figured out how to connect through a proxy... I'm sitting behind a company proxy and I managed to connect via PuTTy Client, so I know my Proxy. I don't need a authentication on the proxy.

I tried with hop: and I tried it with putty. But I don't feel like I know what I have to do.

Is there a description for Dummies how to configure that?
I can connect at home without a proxy and I love the feature, so I don't want to miss it at work.

**Comment by SchoofsKelvin** [comment]
What are your proxy settings configured in the PuTTY session?

If you use `"putty": "my-session"` or something similar in the sshfs config, it _should_ be able to copy (most) proxy settings from the PuTTY session. The extension might not be able to recognize/use some options, though.

**Comment by ThomasSiemens** [comment]
I figured it out.

I needed to reconfigure the connection, pointing directly on the putty session and additionally filled the host in the config itself and now it works. Don't really know what I did wrong but... thank you anyway :)
