### ISSUE TITLE
vscode-sshfs + shellcheck

### ISSUE THREAD

**Issue by PierreGode** [SchoofsKelvin/vscode-sshfs#116]
Hi!
is there any way to make vscode-sshfs work with shellcheck.
I have shellckeck installed on the remote desktop and added 
"shellcheck.executablePath": "/usr/bin/shellcheck",
but no luck, shellcheck works fine on all local files but not on remote ones.
/best resgards Pierre

**Comment by SchoofsKelvin** [comment]
I assume you mean you use the [shellcheck extension](https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck) but it doesn't actually work? This is similar to, if not the same problem as in #42.

Short recap: Extensions right now only work with local files, as VSCode doesn't currently have an API for extensions to interact with remote files provided by other extensions. Also, once that does get added, it still takes a while before extensions make use of it. Not to mention that some extensions (like this shellcheck extension) use binaries that only work on local filesystems.

This isn't something I (or the shellcheck extension creators) can fix right now.

**Comment by PierreGode** [comment]
Thank you for you reply! 
yes, sorry I am very new to VScode, yeah I noticed, 
I found and ugly work around creating a local copy and just copy & pasting code.
thank you again!
/Pierre
