### ISSUE TITLE
How to work with mounted file system through terminal?

### ISSUE THREAD

**Issue by BehnamAboutalebi** [SchoofsKelvin/vscode-sshfs#117]
Is there any way to work with mounded filesystem through the terminal in vs code? 

for example, open a remote file from the terminal

```bash
code MountLocation/etc/nginx/nginx.conf
```

**Comment by SchoofsKelvin** [comment]
No, the virtual filesystem is only useable by (and known to) vscode.

Soon there'll be a feature to launch a terminal in vscode over the same SSH connection, so you can run commands on the remote system (#26), but no, local processes (including terminals) can't access the remote system through the extension.

**Comment by Lockedev** [comment]
You can access the remote filesystem in a VSCode terminal quite easily by simply connecting to it via ssh the same way SSH-FS does.

I'm using Windows 10, so to make it quick, I added the following to my Powershell (6) profile ($Home\Documents\WindowsPowershell\Microsoft.Powershell_profile.ps1):

```
# Function that connects to remote server (params hard-coded)
function createSSHConnection {ssh -p #### -l username 10.0.0.###}

# Alias for the createSSHConnection function
Set-Alias -Name linux -Value createSSHConnection
```

So I open a terminal (ctrl+`), type linux [Enter] and I'm logged into the remote system in my VSCode integrated terminal. This does NOT, however, allow you to do what you've mentioned in your example (code MountLocation/etc/nginx/nginx.conf) as that would be "telling" the REMOTE system to open that file in code.

I gave it some thought for a while and couldn't come up with any good solution for the problem you presented. I'll keep looking into it though.
