### ISSUE TITLE
edit or delete configuration

### ISSUE THREAD

**Issue by JricoIsUnique** [SchoofsKelvin/vscode-sshfs#119]
Cannot open configuration, delete nor create a new one.
[shift]+[ctrl]+[P] then type SSH FS: CONNECT... gives old choices, but does not allow me to do anything to the connections. The extension has become obsolete on my system.

**Comment by ycaner06** [comment]
I couldnt create any conf file, this page doesnt work
There isnt any create command on panel
Code version : 1.32.3 user setup
Node.js 10.2.0
V8 6.6.346.32
Windows NT x64 10
![image](https://user-images.githubusercontent.com/12412027/54418621-85229700-4716-11e9-8f17-5fac9e35ab4e.png)

**Comment by 3kami3** [comment]
Your situation is the same as mine.

Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by JricoIsUnique** [comment]
![2019-03-15 14_55_24-SSH-FS Settings - Untitled (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/24529622/54455623-ae512080-4732-11e9-8ee3-cdafd6beccfa.png)

Found out that by running SSH FS: OpenSetti.....configurations, open the window to add new connections. 
@ycaner06 try running VS code as admin

**Comment by SchoofsKelvin** [comment]
I'm working on a new better config system (a bit explained in #81), which required me to (at least temporarily) remove the Delete/Edit commands. Editing configurations directly in User Settings is still possible. I also added a new Settings UI, which you can open with the `SSH FS: Open settings and edit configurations` command. This allows you to create new configurations, and easily edit them. Doesn't support all features/config options yet.

@ycaner06 I noticed that you're using `WorkspaceFolder settings.json`, which after a quick test, seems to indeed have a bug. The `Global settings.json` and entries from `sshfs.configpaths` do work.

I'll be fixing that bug, along with re-adding the commands, "redirecting" to the new UI.

**Comment by SchoofsKelvin** [comment]
I've (for now) removed the `WorkspaceFolder settings.json` option when creating a new configuration in the Settings UI. The `Workspace` should always work now, assuming you have a workspace (e.g. a directory open) (517a313)

The `Create a SSH FS Configuration` and `Edit configuration` commands (and context menu entry) are re-added. They will open the proper screen in the Settings UI. When using `Edit configuration` for merged/duplicate configurations (e.g. one in global and another place with the same name), the UI will first show you a list of locations to pick from (4a98297)

All these changes are now live in version 1.14.4 of the extension.

*Reminder: The new Settings UI is still a bit in beta. Some things, like proxies, can't be configured using the UI. Editing the JSON files still works, and is currently the only way to configure things that the UI doesn't support yet.*

**Comment by ycaner06** [comment]
it works now! thanks.
