### ISSUE TITLE
How can I search files when I get the remote directory?

### ISSUE THREAD

**Issue by cykannie** [SchoofsKelvin/vscode-sshfs#12]
Hi~ 
It doesn't work to search the files by using Ctrl + P.
So, how can I use the file searching function to get something I need when connect to remote directory?

**Comment by SchoofsKelvin** [comment]
That's something I have been looking into (see issue #2), but it's still in development.

I look at [their progress](https://github.com/Microsoft/vscode/labels/search) now and then, and already have something in my head on how to properly implement search for a remote directory without it being too slow.
