### ISSUE TITLE
Can get ssh-agent to work in Linux

### ISSUE THREAD

**Issue by leictreon** [SchoofsKelvin/vscode-sshfs#120]
Hi - this works great when I enter password, but normally I use an ssh-agent. `$SSH_AUTH_SOCK` correctly points to the ssh-agent socket, but it doesn't seem to use it. If I set "passphrase" to true I can enter password it and it connects fine.
here's my config snippet:
```
        {
            "name": "RAS_Python",
            "label": "RAS python",
            "root": "/home/roc/",
            "host": "192.168.1.2",
            "port": 22,
            "username": "roc",
            // I tried both the env var, and socket path itself
             //"agent": "$SSH_AUTH_SOCK",
            "agent": "/tmp/ssh-9zRw9V13lIHP/agent.11119",
            "privateKeyPath": "/home/roc/.ssh/id_rsa",
            "passphrase" : true,
        }
```
and I reload any changes with ctrl-shift-P -> SSH FS reload configurations.

**Comment by SchoofsKelvin** [comment]
I notice you're also using `privateKeyPath`. I'll have to look at how exactly the underlying ssh2 library I use does it, but as far as I remember, private keys have priority over agents. I'll look into this tomorrow, either to allow you to specify the order, or me changing the default order without preventing certain authentication systems from working.

**Comment by leictreon** [comment]
Ah yes! this fixed it - I deleted the setting for private key and it looked just for the agent. I should have realized this. Thank you very much!
