### ISSUE TITLE
Error while authenticating using agent + private key or password prompt

### ISSUE THREAD

**Issue by SchoofsKelvin** [SchoofsKelvin/vscode-sshfs#121]
I am having a similar issue in Windows 10 ver. 1809. My settings are the following:
```
"sshfs.configs": [
        {
            "host": "server",
            "label": "asd",
            "name": "asd",
            "port": 22,
            "root": "/",
            "username": "user",
            "agent": "//./pipe/openssh-ssh-agent",
            "privateKeyPath": "C:\\Users\\Someone\\Documents\\keys\\id_rsa",
            "passphrase": true
        }
]
```

When I try to connect I am getting this error:
"Error while connecting to SSH FS asd: All configured authentication methods failed"

The agent is already running as a service.
The private key has this form:
```
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC, ...
...
-----END RSA PRIVATE KEY-----
```

If I replace the above settings with these and try to connect:
```
"sshfs.configs": [
        {
            "host": "server",
            "label": "asd",
            "name": "asd",
            "port": 22,
            "root": "/",
            "username": "user",
            "password": true
        }
]
```
It prompts me to enter my password again and again. 
After the second prompt it throws this:
"Cannot read property 'resource' of undefined"

Of course it prompts me again to enter the password a 3rd time. I type the password again and it prompts me a 4th time, then if I press the escape button to cancel the 4th prompt it connects successfully.

_Originally posted by @PanosBougas in https://github.com/SchoofsKelvin/vscode-sshfs/issues/85#issuecomment-473494592_

**Comment by SchoofsKelvin** [comment]
This might take a while to properly fix. Either I have to do some hacky stuff to make the ssh2 library play nice, or I'll have to fork it and make it support what I need it to support. Neither will be easy or quick.

**Comment by PanosBougas** [comment]
@SchoofsKelvin Thanks for all of your hard work. I really appreciate it.
Below are the logs for each step of the connection process.

1st set of settings
[sshfs_logs_per_step1.txt](https://github.com/SchoofsKelvin/vscode-sshfs/files/2974632/sshfs_logs_per_step1.txt)

2nd set of settings
[sshfs_logs_per_step2.txt](https://github.com/SchoofsKelvin/vscode-sshfs/files/2974634/sshfs_logs_per_step2.txt)

I noticed that with both settings I get prompted for password/passphrase at least a 2nd time. 
Between the 1st and the 2nd prompt, Output terminal gets restarted and logs of the first connection attempt are getting lost.

I hope this info helps.

Again thanks for all the effort. 👍

**Comment by SchoofsKelvin** [comment]
Are you sure the key is in the agent? (`ssh-add.exe -L`)

I've figured out why it prompts multiple times for the password/passphrase (924b0a43...35b0b32) and released the fix in version 1.14.5 of the extension.

I'm not entirely sure if it also fixes your issue with the first config, though. It could be that the multi-prompting made the passphrase appear empty, but it's weird that the output shows no error (from the underlying ssh2 library).

**Comment by KonstantinosGiannakakis** [comment]
Got the same problem on Ubuntu 18.10.
When I add `"password" : true`, it asks to give my password 2 times, and then fails to connect, but when I delete the above line in the .json file, then it logs me in. Only the resourse error is undefined pops up.

**Comment by PanosBougas** [comment]
@SchoofsKelvin 

Things got better, but I am still having a second prompt when using the **2nd config**. If I give the password at that second prompt it connects though. 

The issue as I see it, is that the whole extension is being restarted ("Activating extensions" appears at bottom left of the screen) after giving the password at the first prompt. The only error I get is through the VS code notifications.

> Cannot read property 'resource' of undefined

Then the second prompt appears and the only strange thing after the successful connection are 2 "!" at the right of the workspace which show the below message when you hover the mouse above them:

> \ Cannot resolve workspace folder. Cannot resolve workspace folder 
Besides that, everything else works as expected.

The **1st config** is suffering from the **extension restarting issue** too, which causes the second prompt. I added the key to the ssh-agent.exe (thanks for pointing that out) also I removed the "passphrase" and "privateKeyPath", added the "password: true" and then I was able to connect.

I noticed that if I reload the VS Code I was able to connect on the first prompt without errors. But if I do a manual disconnect and try to re-connect again I got the **extension restarting issue** with the second prompt again.

**Comment by SchoofsKelvin** [comment]
I'm able to _kind of_ replicate the prompt-before-reload issue. It seems like vscode is trying to access `newWorkspaceRoot/.vscode/settings.json` before the reload happens. I'm not sure whether this behavior is new, but I'm looking for a way to fix it without assuming too many things (which could otherwise possibly break future features)
