### ISSUE TITLE
Re-writing a deleted config file on SSHFS doesnt pick up the new file. 

### ISSUE THREAD

**Issue by sujiths93** [SchoofsKelvin/vscode-sshfs#125]
I had some issue with the connection on SSHFS, I deleted the existing config file and created a new config having the same name as the previous one, this new config file didn't get picked up.
To resolve it I had to restart VSCode and go through the same process.

**Comment by SchoofsKelvin** [comment]
When VSCode's setting files (Global/Workspace settings.json) change, the extension gets notified and reloads all configs. When one of the external files get changed (including being deleted, or being added when absent), nothing happens. There is a command `SSH FS: Reload configurations` which will re-read all files, including new ones.

If you change something using the UI (`SSH FS: Open settings and edit configurations`), it'll also reload everything. Manually editing/adding/deleting files isn't really recommended. But there's nothing wrong with doing it, as long as you don't break the config, and remember to run the reload command.

**Comment by sujiths93** [comment]
I remember editing them via the UI text boxes.

**Comment by SchoofsKelvin** [comment]
> I remember editing them via the UI text boxes.

Currently, the UI doesn't support adding/deleting config files. You can only add/remove/edit configs themselves (in config files), which would also trigger the reloading.
