### ISSUE TITLE
add task.json but not work

### ISSUE THREAD

**Issue by firechickrsx** [SchoofsKelvin/vscode-sshfs#128]
I use vscode in ms-windows and use sshfs to connnect to centos7.6.
Then I add a default task.json to the directory in centos7.6.but I can`t find task name in task list.
if add task.json in ms-windows directory,it work.

Is it a bug or is sshfs only support file edit?

**Comment by firechickrsx** [comment]
I found it work when I restart the vsCode or do command"reload window"!

There is a similar issues at https://github.com/Microsoft/vscode/issues/24796

**Comment by SchoofsKelvin** [comment]
While I'm not sure if it's the exact issue you linked, but it does seem like it is indeed a bug in VSCode, not the extension.
