### ISSUE TITLE
Group configurations together in folders

### ISSUE THREAD

**Issue by Yakimean** [SchoofsKelvin/vscode-sshfs#130]
Hello, 
One Question , 
not Option for created any Folder,fields on the sshfs.configs  ....
because when you have a long List of server connection  is can be really cool to classified by group.
or may be I have missed the  way for make the configuration.
If you have any idea.
Best regard

**Comment by SchoofsKelvin** [comment]
I'll look into adding a `group` property to group configurations together, for your so-called folders. It'll take me a little while to make the UI (both the Explorer tab and Settings UI) work with it. It won't change how the config files themselves look though, although you aren't really supposed to directly interact with them anyway.

**Comment by SchoofsKelvin** [comment]
I've implemented this feature (d5af8b4...d9a2236) and it's now live in version 1.16.1 of the extension.

Use the Settings UI to add a config to a group. There's a new field "Group" (under "Label") where you can set the group name, e.g. `MyGroup`, or `MyGroup.Sub.Group`. A group can consist of both configs and other groups, so you can use it pretty much however you like.

The Settings UI's homescreen now has a button to switch between grouping/sorting by location, and by grouping/sorting by the new group field. In the latter mode, it'll only show groups that have configs. E.g. if you only have one config with as group `MyGroup.SubGroup`, it'll display that group, but not `MyGroup` on its own.

The tree view in the Explorer tab does the same, except it uses collapsing tree nodes for each group. It's very intuitive, while not easy to explain.
