### ISSUE TITLE
use the extension when using a jumpbox

### ISSUE THREAD

**Issue by pablomedrano10** [SchoofsKelvin/vscode-sshfs#132]
Is it possible to use the extension when you first have to ssh into a jumpbox and from that machine to another where your files are? I was using the extension for other servers but I am forced to use that set up now

**Comment by SchoofsKelvin** [comment]
I think you mean SSH hopping (#7), which I just added support to in the Settings UI. Editing a config in the UI should show a config option "Proxy", which is a dropdown with "SSH Hopping", after which you can select the config to use as hop.
