### ISSUE TITLE
Stop storing passwords in plain text

### ISSUE THREAD

**Issue by pwaterz** [SchoofsKelvin/vscode-sshfs#134]
I use the sync plugin to back up my configuration and noticed this plugin stores passwords in plain text. This should be fixed.

**Comment by SchoofsKelvin** [comment]
There isn't really an easy and secure way to store passwords otherwise. The recommended way is using private keys or agents. Mind that both the Password and Passphrase field both support prompting, which will mean it'll prompt you to enter the password when connecting to the remote file system.

I'm closing this, as it isn't a big issue (extension supports prompting/agents) nor is there a secure way to store passwords without introducing another password. If you have any ideas, feel free to suggest them.

**Comment by pwaterz** [comment]
Something as simple as using a salt to hash the passwords would be better no?

**Comment by SchoofsKelvin** [comment]
> Something as simple as using a salt to hash the passwords would be better no?

That isn't possible. The extension needs to know the actual password to send to the server or unlock the private key. Storing it as a hash (salted or not) would prevent that.

> Also what is your reasoning for it not being a big issue?

Like I mentioned in my previous reply:
- People can use private keys, or even better, agents. Then the extension doesn't need passwords
- People can alter the config to prompt for the password/passphrase when needed

**Comment by pwaterz** [comment]
You could un hash the password then send it.

It's incredibly insecure to even allow someone to store a ssh password in clear text. There definitely has to be a better way of dealing with this.

**Comment by SchoofsKelvin** [comment]
> You could un hash the password then send it.

No, that's not how hashing works. Hashes are (supposed to be) irreversible. 



> It's incredibly insecure to even allow someone to store a ssh password in clear text. There definitely has to be a better way of dealing with this.

The main reason for private keys and agents, besides ease of use

**Comment by pwaterz** [comment]
Alright well I guess I need to stop using this. Cheers.

**Comment by pwaterz** [comment]
FYI this is what Remote System Explorer does https://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.rse.doc.user%2Ftasks%2Ftbeginpass.html at least there is a little bit of security.

**Comment by SchoofsKelvin** [comment]
> FYI this is what Remote System Explorer does https://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.rse.doc.user%2Ftasks%2Ftbeginpass.html at least there is a little bit of security.
@pwaterz 

That's what I meant before:

> I'm closing this, as it isn't a big issue (extension supports prompting/agents) nor is there a secure way to store passwords without introducing another password.
@SchoofsKelvin 

Encrypting the configs (or just the passwords, at least) would require prompting for another password. At that point, you might as well just enable the prompt for your configuration itself.

**Comment by pwaterz** [comment]
I would remove the option complete to store the password then.

**Comment by SchoofsKelvin** [comment]
> I would remove the option completely to store the password then.

There's no need to remove the option. People can freely choose to switch to prompting, private keys or agents.

**Comment by pwaterz** [comment]
I think otherwise. I managed to publish a public gist using the sync plugin that had all the info required to connect to a work computer. Luckily I thought to check and see what this plugin did and deleted it right away. I think others won't be so lucky.

**Comment by SchoofsKelvin** [comment]
In the User Settings (or even Workspace Settings), you can configure `"sshfs.configpaths"` to read SSH FS configurations from other files. Files which you can add to your .gitignore, or is out of range of your sync plugin.

**Comment by pwaterz** [comment]
Again most people will never know that. So I feel like that point is moot. Quoting Rob Pike "Simplicity is complicated"
