### ISSUE TITLE
ssh port error

### ISSUE THREAD

**Issue by mithereal** [SchoofsKelvin/vscode-sshfs#137]
cannot connect to any port other than 2x i need to connect to port 8000

**Comment by SchoofsKelvin** [comment]
I assume you changed the Port config field to 8000? Are there any errors?

Post your `Output > ssh-fs` here. You can censor hostnames, usernames, ... if preferred. Passwords/passphrases should be automatically censored, but check to be sure.

**Comment by mithereal** [comment]
also there is an issue if you try to backspace to delete the port it will automatically force 22 on you id like to be able to blank the port w/o having to mouseclick before the 22 and add 8888 then del the 22 from the result, 
[ERROR] Error while connecting to SSH FS house_of_graphix:
spawn REG ENOENT
[ERROR] spawn REG ENOENT
Error: spawn REG ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
[INFO] Loading configurations...
[DEBUG] 	Added configuration house_of_graphix from 1
[INFO] Found 1 configurations
[INFO] [house_of_graphix] Calculating actual config
[WARNING] [house_of_graphix] 	Configurating uses putty, but platform is linux
[INFO] Fetching PuTTY sessions from registry
[ERROR] Error while connecting to SSH FS house_of_graphix:
spawn REG ENOENT
[ERROR] spawn REG ENOENT
Error: spawn REG ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
