### ISSUE TITLE
always loading when open a new file

### ISSUE THREAD

**Issue by yyn19951228** [SchoofsKelvin/vscode-sshfs#138]
My issue is that when a new connection established, I can only open the first file, and when I want to open another file, the vscode will just get stuck on loading, and show nothing. 

<img width="1195" alt="Screen Shot 2019-05-02 at 12 29 39 PM" src="https://user-images.githubusercontent.com/12838556/57090952-10131d00-6cd6-11e9-9056-c4829d755e44.png">

the file I am showing is train.py, and I want to open test.py, but it just keep loading, and show nothing.

**Comment by SchoofsKelvin** [comment]
What OS are you running VSCode on, and what OS is the server you're connecting to?

Post your `Output > ssh-fs`. You can censor hostnames, usernames, etc. Passwords/passphrases should be automatically censored, but it doesn't hurt checking.

**Comment by yyn19951228** [comment]
The OS I am using is MacOS Mojave 10.14.4

The server I am connecting to is Ubuntu 16.04 on Google Cloud Platform.

Here is the image from `Output > ssh-fs`
<img width="792" alt="Screen Shot 2019-05-03 at 11 37 38 PM" src="https://user-images.githubusercontent.com/12838556/57173359-83af4a00-6dfc-11e9-9517-693e92c74bd3.png">

and the image from `Output > Log(Window)` when I want to save a `.py` file on server by using ssh-fs
<img width="1342" alt="Screen Shot 2019-05-03 at 11 37 48 PM" src="https://user-images.githubusercontent.com/12838556/57173358-83af4a00-6dfc-11e9-81ed-d0fb3d9a2ebf.png">

I am not sure whether the problem is on my VSCode, or my system or on the ssh-fs extension.

**Comment by yyn19951228** [comment]
And my vscode version is 1.33.1

**Comment by SchoofsKelvin** [comment]
From the `onWillSaveTextDocument` warning, it seems like you have another extension, which is trying to do something with git when saving the document, but fails. Your VSCode is probably configured to save the current document when switching documents. I'm not sure if that's what causing the UI to hang.

Could you try disabling all other extensions and seeing if this bug still happens?
