### ISSUE TITLE
Drop project and contribute to official remote extension

### ISSUE THREAD

**Issue by WSLUser** [SchoofsKelvin/vscode-sshfs#139]
Microsoft just announced a new feature: https://code.visualstudio.com/blogs/2019/05/02/remote-development which in theory would be more supportive than what this extension can do.  However as it's in preview, there are features missing which this extension provides. Therefore I think it would be a better investment of time and energy to take the functionality that is lacking in https://github.com/Microsoft/vscode-remote-release/issues from this extension and serve as a single source for issues and feature requests. Why have duplicate effort? 

One feature is the ability to copy files from the File Explorer to local.

**Comment by SchoofsKelvin** [comment]
It's definitely something I'll be looking into, but I'll (also) keep working on this extension for now. I don't really have the time to deepen me into their source code, which I couldn't even find after a quick search.

**Comment by WSLUser** [comment]
Yeah the only one I see available is containers. But it's supposed to be OSS. I filed an issue requesting they release the source-code as they should.
