### ISSUE TITLE
Not Find in folder with SSH FS

### ISSUE THREAD

**Issue by yiangshieng** [SchoofsKelvin/vscode-sshfs#140]
I cannot use the "Find in Folder" function when using SSH FS
http://www.fsend.vn/download/RW5N_-VSMNuytO1w4j3oc2QujJo1grmF

**Comment by SchoofsKelvin** [comment]
Searching (including Ctrl+O file search) aren't supported yet. I'm waiting for the SearchProvider API to be released, see #2 for more information.
