### ISSUE TITLE
SSH Key Passphrase

### ISSUE THREAD

**Issue by nessor** [SchoofsKelvin/vscode-sshfs#143]
I noticed that when entering the password for the private key, it is not hidden. It is clear that the password is stored in plain text, but a hidden input would be useful for office environments!

**Comment by SchoofsKelvin** [comment]
Passphrase can be configured to be prompted using a "star censor" input. Same for the password.

**Comment by clementaudic** [comment]
To be asked for your passphrase at each connection instead of storing it in plain text, set the Passphrase field to `<Prompt>`.
