### ISSUE TITLE
Close all connections

### ISSUE THREAD

**Issue by hansenconnor** [SchoofsKelvin/vscode-sshfs#144]
Hello!

It is a timely process to right click and disconnect each workspace folder - wondering if a 'Disconnect All' option would be appropriate?

**Comment by SchoofsKelvin** [comment]
If the workspace folder is removed, the session is disconnected. You can use `Ctrl+K F` (`File: Close Workspace` command) to close all workspace folders, disconnecting everything. Right now, there indeed isn't any shortcut for removing _just_ the ssh-fs workspace folders when in a multi-root workspace with also non-ssh-fs workspace folders.

**Comment by SchoofsKelvin** [comment]
New connection manager (70d38ee) comes with a Connections view, allows quickly closing a connection _(~ one config)_ with a button, while also providing a "Disconnect all" command and button in said view:
![image](https://user-images.githubusercontent.com/14597409/102398293-60d8a600-3fdf-11eb-9f54-1b8951bf5ff5.png)
