### ISSUE TITLE
Mac host config breaks on reboot

### ISSUE THREAD

**Issue by Robbie4AU** [SchoofsKelvin/vscode-sshfs#145]
When a config is made for a Mac host and that Mac is rebooted, the configuration breaks completely. This requires a full deletion and recreation.

Notes:
- No errors appear, connection is just unresponsive.
- Tried editing config and saving/refreshing
- Tried restarting VSC

**Comment by SchoofsKelvin** [comment]
Can you copy-paste the config as it appears under `sshfs.configs` in your settings.json? There shouldn't be any reason that rebooting breaks a config. Especially if completely deleting and recreating it fixes it until the next reboot.

**Comment by Robbie4AU** [comment]
I redacted the personal stuff, but here it is


   ```
 "settings": {
        "sshfs.configs": [
            {
                "host": "host.address.com",
                "name": "mac-mini",
                "password": "Password1!",
                "root": "/Users/user123/appFolder",
                "username": "user123"
            }
        ]
    }
```

**Comment by SchoofsKelvin** [comment]
This really doesn't make any sense. Recreating a config shouldn't change anything. Worst case, restarting vscode (e.g. weird caching issue) or rebooting the target server (e.g. SSH anti-DDoS measures) might fix an unknown bug, but recreating a config with the exact same contents shouldn't have any effect.

I'll keep this issue in the back of my mind, but unless there are other people with the same problem and/or there's any indication of what exactly is going wrong, I'm not too hopeful about figuring this out.

**Comment by Robbie4AU** [comment]
I understand. Probably fringe case but I at least wanted you to note it
