### ISSUE TITLE
Can't resolve ".local" (mDNS) hostnames

### ISSUE THREAD

**Issue by bitrevo** [SchoofsKelvin/vscode-sshfs#146]
I would like to connect to my local private servers via `myserver.local` hostname, seems like it is not currently supported in `vscode-sshfs`, is it possible to support this feature?

**Comment by SchoofsKelvin** [comment]
This seems related to #124, although that's just about regular DNS, not mDNS. You could try alternative hostnames like `myserver.home` and just `myserver`.

If `dns.lookup` doesn't work with any of those, I can only suggest using the direct IP. I'm not directly planning on adding mDNS, as it needs certain binaries to be installed on the system.
