### ISSUE TITLE
Is there a way to use code navigation along with SSHFS?

### ISSUE THREAD

**Issue by YaboLee** [SchoofsKelvin/vscode-sshfs#153]
I find when I browse/edit files remotely, there is no originally enable extensions like code navigation and auto-format. Is there a way to config it or fix it? 

I think it may be a problem for vscode itself?

**Comment by SchoofsKelvin** [comment]
It's not really an issue caused by this extension. It's just that other extensions don't know how to handle remote filesystems, along with the fact that vscode also doesn't provide any API to help with that.

More info can be found here: #42
