### ISSUE TITLE
Any plans to port this to code-server?

### ISSUE THREAD

**Issue by demyxco** [SchoofsKelvin/vscode-sshfs#155]
At the moment, opening the config errors.

**Comment by SchoofsKelvin** [comment]
This would kind of defeat the purpose of this extension. The goal here is to be able to connect to a remote filesystem over SSH and edit the files that way. The whole code-server project basically does the same, but more in-depth, basically running the IDE on the remote system. I don't really see why you would want this extension in combination with code-server.

As for the config errors, I haven't tried code-server yet, but config errors should only appear if there's actual an error in the config, which would also error when *not* using code-server.

**Comment by fellwell5** [comment]
I want this because i want to host my own cloud ide to develop on multiple servers in my browser.
My problem is that the ssh fs won't appear as workspace.
Could you help us?

**Comment by demyxco** [comment]
@fellwell5 your best option is to just install sshfs on your server and then mount them, works nicely with code-server!
