### ISSUE TITLE
Use default login credentials on Linux

### ISSUE THREAD

**Issue by maep--** [SchoofsKelvin/vscode-sshfs#156]
From Linux, when I try to log into any machine it keeps asking for my username, and then key authentification fails.

This is my config, it should be sufficient to connect to any of our machines:
        {
            "host": "foo707",
            "name": "foo707"
        }

I expect sshfs to behave like regular ssh where `ssh foo707` works without explicitly providing user name and credentials. Default root should be the user's home directory on that machine.

**Comment by SchoofsKelvin** [comment]
The username field supports environment variables, so `$USERNAME` should work. As for the root path, it defaults to `/`, but can also be configured to `~`, which will resolve to the home directory of the user you connect as.

**Comment by SchoofsKelvin** [comment]
The username field now suggests `$USERNAME` (a318cdc), now published under version 1.16.3 of the extension.
