### ISSUE TITLE
JS Intellisense/Document Formatter not working in SSH workspace

### ISSUE THREAD

**Issue by TunaLatte** [SchoofsKelvin/vscode-sshfs#16]
Internal Javascript formatter not working in sshfs workspace. (workaround is using Beautify - which doesn't handle JSX well)
CSS, HTML, JSON etc work fine.
I'm not sure what logs I should provide.
Thanks.

**Comment by SchoofsKelvin** [comment]
This might be a "bug" in the formatter where it operates on files on the local disk. I'll see if I can find the real (possibly different) cause and fix it.

**Comment by SchoofsKelvin** [comment]
I've checked the vscode issue (Microsoft/vscode#51700) and ran some checks. I'll close the issue for now, as this doesn't seem to be something I can fix.
