### ISSUE TITLE
Enhancement: "code" command line support

### ISSUE THREAD

**Issue by talsaiag** [SchoofsKelvin/vscode-sshfs#160]
Hi,

Amazing plugin!

I would like to open a file, on a remote host from the (local host) command line, for editing using vscode.

Using your plugin I am able to connect to a remote host of my choosing (using env variables) but I could not seem to make vscode open a remote uri...
When such a file is opened, maybe even select it in the remote file system?
Also support line number (and column)?

Since I have multiple servers, I'm using:
export VSCODE_USERNAME='username' && export VSCODE_REMOTE_HOST='remote_ip' && code

Another issue, to complete this enhancement request, is when I'm using env variables to connect to a remote host, I would like it to default to do-not-establish an ssh connection if they are empty (so using vscode locally won't bug me with inputing the username for the remote file-system connection...).

(working on mac, if that makes any difference)
Thanks,
Tal

**Comment by SchoofsKelvin** [comment]
I think vscode supports opening URL schemes registered by extensions. You could try opening `ssh://configname/path/relative/to/root` from the command line. If the config requires you to enter your username/password, it'll prompt for that after vscode started.

The extension will only connect to configs if there are workspace folders pointing to them, or alternatively, directly opening a file by URL, as given above. E.g. the config `test` would only connect if you have a workspace folder with an URL starting with `ssh://test/`, or you have a file open in your editor which URL starts with `ssh://test`.

**Comment by talsaiag** [comment]
running `code ssh://configname/path/relative/to/root` opens local file `~/ssh/configname/path/relative/to/root`

**Comment by SchoofsKelvin** [comment]
I'm looking around a bit, e.g. Microsoft/vscode#4883, but I can't really find one that works for custom schemes. The `--file-uri` option defined in `code -h` doesn't help either.

You could try adding a feature request to vscode to support opening files from custom schemes.

**Comment by talsaiag** [comment]
thanks!
https://github.com/microsoft/vscode/issues/76533

**Comment by WSLUser** [comment]
They probably have the feature but closed-source in the Remote-SSH extension.

**Comment by SchoofsKelvin** [comment]
While directly using `code ssh://...` still isn't supported, `code --file-uri ssh://a/file` and `code --folder-uri ssh://a/folder` are now.
