### ISSUE TITLE
How to switch user on remote server?

### ISSUE THREAD

**Issue by A-R-P-I-T** [SchoofsKelvin/vscode-sshfs#161]
Hey, Is there a way to change the current user on the server. The current user that logs in might not have permissions to modify files but he can switch to another user on the server and modify the files. Is there a way to do this ? If not, can this  be added as an enhancement ? or maybe can someone point me as to where I need to make changes ? I'd appreciate any help. Thanks!!

**Comment by WSLUser** [comment]
> but he can switch to another user on the server and modify the files.

You'll have to do it in a terminal. I'm not the creator but I'm pretty sure this isn't possible without a lot of _effort_. Basically he'd need to support everything OpenSSH has to offer. That would require a dependency on third party software, which is actually how the VS Remote-SSH works actually (OpenSSH is required to be installed, which can be an issue for Windows.)

**Comment by pablomedrano10** [comment]
I was just wondering if that was possible too

**Comment by wolfclostermann** [comment]
It would be great if the following workaround could be incorporated, which would allow this functionality:

sftp -s "sudo /usr/libexec/openssh/sftp-server" target.server.address

**Comment by SchoofsKelvin** [comment]
There's actually a (although a bit of an experimental) way of using sudo: https://github.com/SchoofsKelvin/vscode-sshfs/issues/104#issuecomment-467150071

This requires you to set up the config to use sudo for everything. It's indeed not possible (or at least easily implementable at this point) to switch user or access some file as another user mid-connection.

@wolfclostermann If you open your `settings.json` file, scroll to your sshfs config and add `"sftpSudo": "username"`, the extension will actually use `sudo -u username /usr/lib/openssh/sftp-server` internally, sending (or prompting) for a password if it detects sudo asks for it. There's also a config option `sftpCommand` which will make the extension start a shell and run that command to create a SFTP connection. _Mind that if `sftpCommand` starts with `sudo`, it'll auto-convert your config to use `sftpSudo`, to deal with password prompting in its own way._
