### ISSUE TITLE
Issue after vscode update to 1.36.0

### ISSUE THREAD

**Issue by gmtechworks** [SchoofsKelvin/vscode-sshfs#162]
Error while connecting to SSH FS "connection name":
Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR

**Comment by badcrc** [comment]
I'm getting an openssl error too after updating to 1.36.0:

```
Error while signing data with privateKey: error:06000080:public key routines:OPENSSL_internal:UNSUPPORTED_ALGORITHM
```

I've tried with a RSA and a DSA keys and both fails.

**Comment by sikmike** [comment]
I can confirm. I am getting the same error connecting to an AWS linux server:

```
Error while connecting to SSH FS mydev:
Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR
```

**Comment by dolbyac3** [comment]
Upgraded to vscode 1.36 and get the following error:
```
Error while connecting to SSH FS web1:
Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR
```
Reverted back to vscode 1.35.1 and everything works fine.

**Comment by boeningc** [comment]
Same issue.

Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by jacobmata** [comment]
Same for me after upgrading VSCode
`Error while connecting to SSH FS do2: Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR`

**Comment by rotexhawk** [comment]
Same issue on mac.

**Comment by SchoofsKelvin** [comment]
I'm not entirely sure what's going on. It seems like vscode upgraded Electron to 4.x, which uses a new SSL library that dropped support for some key types.

The weird thing is that RSA _should_ still be supported, but @badcrc had an issue with that too?

Version changes:
- vscode 1.36 upgraded node 10.2.0 to 10.11.0
- node 10.9.0 updated OpenSSL from 1.1.0h to 1.1.0i
- upgraded to Electron 4
- Electron switched to BoringSSL _(apparently overriding node's version)_

Similar issues:
- liximomo/vscode-sftp#594
- microsoft/vscode#77500
- electron/electron#16195 **(actual cause)**

**Comment by badcrc** [comment]
I've just tried with a rsa key and seems to work, maybe I didn't try it right the first time.

**Comment by SchoofsKelvin** [comment]
I'll keep this issue open for a while and keep looking around, but right now it seems like it's not something I can fix, without dynamically converting keys if that's even possible.

**Comment by dolbyac3** [comment]
I think it has to do with the key bit size. 

I was using some older rsa keys so I re-generated some with a bit size of 4096 (`ssh-keygen -t rsa -b 4096`) and they worked with this plugin running on vs code 1.37.1. 

Then I generated some new keys with the default bit size (2048) and they did not work.

So if you are having trouble try generating a stronger rsa key.

**Comment by rotexhawk** [comment]
I am able to login to my remote servers after the recent VScode update. 1.37.1

**Comment by over-engineer** [comment]
@dolbyac3 Yes! Thank you! I was going crazy while trying to fix an issue on an Electron app for the past 3 hours. You really saved my bacon.

**Comment by Trimakas** [comment]
Shoot, still having this issue. tried PEM format and the 4096 length format, both with no luck.. anyone else still having this issue?

**Comment by jorgehumberto** [comment]
having the same issue here. I am on:
- Fedora 31 (64)
- vscode 1.40.2
- shfs 1.16.3

**Comment by SchoofsKelvin** [comment]
This should be fixed after updating ssh2 (b22dd71) and VSCode updating their node version.

**Comment by dylanh724** [comment]
Andd it's back

**Comment by SchoofsKelvin** [comment]
The extension is already using `ssh2@0.8.9` which in turn uses `ssh2-streams@0.4.10`, both the latest versions.
Need to wait on `ssh2` to complete its rewrite, or accept this PR: mscdex/ssh2-streams#164.
