### ISSUE TITLE
Issue connecting to remote - Putty - Remote directory

### ISSUE THREAD

**Issue by kurtjcu** [SchoofsKelvin/vscode-sshfs#164]
Having a few issues with the latest couple of updates to VSCode.
I have a connection that uses putty AND connects to a specific remote directory. Sometimes it connects fine, other times it does not connect and requires several restarts of vscode to connect properly.

Error:
"Path '/home/aaa/bbb/ccc/' in SSH FS 'external_ubuntu' is not a directory"

**Comment by SchoofsKelvin** [comment]
You're trying to access `/home/aaa/bbb/ccc/external_ubuntu` or where exactly does this `external_ubuntu´ come from? And what did you configure as root directory?

**Comment by kurtjcu** [comment]
"external_ubuntu" is the name of the SSH-FS config.
'/home/aaa/bbb/ccc/' is the path (root in config)

**Comment by SchoofsKelvin** [comment]
Does the user you're connecting as have read and execute access to that directory? Or is that path a kind of symlink?

**Comment by kurtjcu** [comment]
It is the users home directory, full rights. One thing I have noticed and I am not sure if it is related is that using the ssh plugin it seems to restart my platformio plugin?
