### ISSUE TITLE
Question associated with issue #156

### ISSUE THREAD

**Issue by Al7ech** [SchoofsKelvin/vscode-sshfs#165]
I'm trying to connect to my machine with ssh fs using ~/.ssh/config file.

And I get the same error from #156. 

From the issue #156 , I understood that adding "username":"$USERNAME" would fix the problem. But still ssh fs gives me the same error(asking username, then "Error while connecting to SSH FS server:
getaddrinfo ENOTFOUND server server:22" pops out).

Am I understanding something wrong?

here's my settings

{
            "host": "server",
            "root": "~/",
            "username": "$USERNAME"
       }

**Comment by SchoofsKelvin** [comment]
Depending on your operating system you're running vscode on, you might have to use `$USER` instead of `$USERNAME`. I'll see about making the Settings UI suggest `$USER` or `$USERNAME` depending on which one is found on the OS, otherwise possibly mapping one to the other by default.

**Comment by Al7ech** [comment]
According to my OS (mac OS Mojave version 10.14.4) both `$USER` and `$USERNAME` exists.

If the release version doesn't use config file, I should set the `settings.json` files. Thanks.
