### ISSUE TITLE
Use cpp headers on local machine for intelliSense

### ISSUE THREAD

**Issue by lukas-bernhard** [SchoofsKelvin/vscode-sshfs#168]
My goal is to get intelliSense support for the remote development of a C++ project. As has been explained in other issues, it is currently not possible to include headers from the remote folder in the c_cpp_properties.json. 

However, would it be feasible to point intelliSense to header files on the local machine? That would get me at least basic support for the C++ STL and some dependencies.

So far, I have not managed to set this up successfully and I apologize if it is painfully obvious that this will not work. I'm afraid I don't have good understanding of the mechanics involved.

Thanks and best regards,
Lukas

**Comment by SchoofsKelvin** [comment]
This would solely depend on whether the C++ IntelliSense extension supports this feature. You'll have to check with the developers of that extension.

Using [VSCode Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) (especially using [SSH](https://code.visualstudio.com/docs/remote/ssh)) might be your best bet here.
