### ISSUE TITLE
env variable is not parsed in 1.7

### ISSUE THREAD

**Issue by badaz** [SchoofsKelvin/vscode-sshfs#17]
Hi, thanks for your work, this extension is great ! However I can't manage to use the $SSH_AUTH_SOCK variable to define the ssh agent under the "agent" key in the config. I checked on my system and it is defined : ```echo "$SSH_AUTH_SOCK"``` outputs /tmp/ssh-Oq2ohv1xpwP9/agent.4681, but when I try to connect I get this message : ENOENT $SSH_AUTH_SOCK, as though the variable was not parsed at all. I checked the code in the out folder of the installed extension, and the replaceVariables function is present and the code makes calls to it in the connect.js. Did I miss something ? I tried to open dev tools and parse my string the same way you do it in the  replaceVariables function and it does manage to output /tmp/ssh-Oq2ohv1xpwP9/agent.4681. If you have any insight about this I'd be happy to hear it. Thanks again !

NB : I tried with the absolute path of the socket, it works fine and manages to connect

**Comment by SchoofsKelvin** [comment]
Ah, it seems the variable replacing only happens when it's a PuTTY session.

I've fixed the issue (313721e) and published it. Could you confirm that it's fixed for you after updating to 1.7.1?

**Comment by badaz** [comment]
It works, you fixed it! Thanks for the quick answer and fix! You can close the issue.

I have a question although it's not directly related: will you implement search ? What about the other things like linting, etc ? Is it even possible to make them work?

Thanks again!

**Comment by SchoofsKelvin** [comment]
With vscode 1.24 came the proposed API for the SearchProvider, which I'll be working on (#2) now. Once that's implemented (and released in (hopefully) 1.25), search should work again. Whether linting, intellisense, ... will work or not, not entirely sure.

**Comment by badaz** [comment]
Great news! Thanks
