### ISSUE TITLE
Error while reading the keyfile at:/path/to/id_rsa

### ISSUE THREAD

**Issue by ksivaman** [SchoofsKelvin/vscode-sshfs#170]
I am trying to connect to a server via a private key and a passphrase. I have entered the absolute path but still get the error:

> Error while connecting to SSH FS benjy: Error while reading the keyfile at: /home/ksivaman/.ssh/id_rsa

**Comment by dlarmgo** [comment]
Well, faced with it too and it's kinda frustrating. It started work only after I choose path to file by "prompt" button and ui directly. After that move it works well, even with previously entered file paths.

**Comment by SchoofsKelvin** [comment]
It's better using the Settings UI over manually editing the settings.json anyway. Although, there shouldn't be a reason absolute paths in the settings.json should fail, apart from using `\` instead of `\\` in JSON strings.

**Comment by dossymbekov** [comment]
Worked for me with $HOME/.ssh/id_rsa. 

Did not work with other variable:  $PWD
Did not work with relative path:  ~/.ssh/id_rsa
Did not work with absolute path:  /Users/<localuser>/.ssh/id_rsa
