### ISSUE TITLE
extension host terminates unexpectedly after opening ssh files.

### ISSUE THREAD

**Issue by laurencefass** [SchoofsKelvin/vscode-sshfs#171]
This is happening a lot with those annoying self-updates to vscode. I often have to restart half a dozen times to get it to work...

Everything is fine until i open a file under SSH FS. Then I lose the SSH File Systems tab and the VPS SSH workspaces are disabled.

To reiterate I can traverse the file system but opening a file is breaking vscode.

vscode version info.

`Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
`
thanks

**Comment by laurencefass** [comment]
the last time i tried this opening a file under SSH FS actually crashed the app. directory traversal was working fine.

**Comment by laurencefass** [comment]
reverting to version 16.2 removes all the problems. looks like a 16.3 issue. please let me know if i can be of any assistance with logs etc.

**Comment by SchoofsKelvin** [comment]
A lot of the connection establishing has been rewritten in 1.18.x, does this issue still happen?
