### ISSUE TITLE
Code Outline not working on files in SSH workspace

### ISSUE THREAD

**Issue by andy-slac** [SchoofsKelvin/vscode-sshfs#18]
I'm not sure whether this is SSH FS issue or VSCode issue, but I see that for files that I open on SSH FS workspace there is no outline generated at all. Outline panel stays empty no matter what I do, while it works OK for local files.

**Comment by SchoofsKelvin** [comment]
Sounds like it's an issue with Code Outline only working with the hard disk for now. I'm working on adding the search feature (#2) which might solve this, but it's most likely something I can't fix for now.

**Comment by valen214** [comment]
Would it be possible to cache remote file on local hard disk,
then only upload those cache file to remote site through ssh on change.
(This is actually the way notepad++ plugin implemented)

**Comment by SchoofsKelvin** [comment]
Caching files locally wouldn't change much, unless I change the whole extension to only create and maintain these "cache folders". Those would also have to contain *everything* on the remote server for plugins/extensions to work fine. Possible, but not the goal of this extension.
