### ISSUE TITLE
Ansible No Auto-Completion or Snippets

### ISSUE THREAD

**Issue by 40w-26292** [SchoofsKelvin/vscode-sshfs#182]
After installing this module with the Microsoft Ansible module, auto-completion and code snippets for Ansible are broken when editing remote files. 

See issue for additional information:
https://github.com/VSChina/vscode-ansible/issues/185

**Comment by SchoofsKelvin** [comment]
Duplicate of #27.

If you need the full IDE experience for a remote host, you're better off using [vscode's Remote SSH](https://code.visualstudio.com/docs/remote/ssh).
