### ISSUE TITLE
pageant doesn't work correctly.

### ISSUE THREAD

**Issue by richard-scott** [SchoofsKelvin/vscode-sshfs#183]
I have SSH keys loaded in my pageant and when I select this from the "Agent" dropdown, I can't connect to my target system.

However, if I leave "Agent" blank. I can connect.

**Comment by richard-scott** [comment]
I also need to provide a name of a PuTTY session otherwise it won't connect and I get an "All configured authentication methods failed error.

**Comment by SchoofsKelvin** [comment]
Did you specify the PuTTY session name in the `PuTTY` field? If that's left blank, the extension will try to guess the correct session based on the provided host/port/username.

Also make sure vscode and the pageant are running as the same user. Running one but not the other as administrator for example will prevent the extension from using pageant.

**Comment by richard-scott** [comment]
ah, my mistake then. I didn't realise that you **needed** a sensibly named "session" in Putty.
