### ISSUE TITLE
'Create New Configuration' page - cannot save

### ISSUE THREAD

**Issue by devopsmyth** [SchoofsKelvin/vscode-sshfs#184]
I just installed the app and I'm unable to create my first configuration file. When I give it a name and hit save, nothing happens. The cancel button works but the save does not.

**Comment by SchoofsKelvin** [comment]
- Are there any errors in the logs
- Is the `Location` dropdown set to `Global settings.json`?
- Is the `Save` button clickable, or greyed out?
