### ISSUE TITLE
How do I open multiple remote files at the same time, each in a new tab instead of a new view?

### ISSUE THREAD

**Issue by githubcom13** [SchoofsKelvin/vscode-sshfs#195]
Hi,
How do I open multiple remote files at the same time, each in a new tab instead of a new view?
Thank you

**Comment by Simba98** [comment]
Although this issue is closed, can anybody tell me how to do that?

**Comment by SchoofsKelvin** [comment]
Is it even possible to do this for regular files? If not, this is an issue in VS Code and not the extension. VS Code merely asks my extension to get/set the contents/metadata of a file/directory. I don't control the actual editor tabs.
