### ISSUE TITLE
Error while connecting to SSH FS workPC: All configured authentication methods failed  -- no password prompt

### ISSUE THREAD

**Issue by naidoo88** [SchoofsKelvin/vscode-sshfs#196]
Hi there! 

I am trying to connect, via tunnel to my work computer via an ssh tunnel. When connecting, the password prompt appears for "login" and is accepted, however the forward connection then immediately fails and I get the error "Error while connecting to SSH FS npc8:
All configured authentication methods failed"

My config looks like follows:
 
"sshfs.configs": [
        {
            "hop": "login",
            "host": "<remote-ip>",
            "label": "workPC-sshfs",
            "name": "workPC",
            "username": "<username>"
        },
        {
            "host": "<login-tunnel ip>",
            "label": "login-tunnel",
            "name": "login",
            "username": "<username>"
        }
    ]

Thanks in advance!

**Comment by naidoo88** [comment]
Any help would be deeply appreciated!

**Comment by PierreMarchand20** [comment]
I had a similar issue and adding to the settings `"password": true` solved the issue.

**Comment by naidoo88** [comment]
What a simple fix!! 
Thank you so much for taking the time to answer.
