### ISSUE TITLE
Add Support for PuTTY "Local" Proxy Configuration

### ISSUE THREAD

**Issue by securityguy-nc** [SchoofsKelvin/vscode-sshfs#199]
![image](https://user-images.githubusercontent.com/6675130/83446618-342abb80-a40c-11ea-954e-6dc4372ee3aa.png)

The above configuration allows PuTTY to transparently connect through a jump box. 

However if I try to use this PuTTY configuration, I get an error:
`Error while connecting to SSH FS devserver: The requested PuTTY session uses an unsupported proxy method`

**Comment by SchoofsKelvin** [comment]
The extension can only read/support the None, SOCKS 4/5 and HTTP proxy types.

In your case, it seems like you're basically just doing a SSH hop? The extension does support SSH hopping, which can be configured using the Settings UI or editing settings.json:
```jsonc
{
    "name": "...",
    "hop": "jumpbox"
    // ...
},
{
    "name": "jumpbox",
    "host": "jump-box.org.com",
    // ...
}
```

This basically makes the extension create a SSH session to `jumpbox`, then use it to create a SSH tunnel to the actual host. Looking at your screenshot, this should be what you want.

More info is also available in previous issues: #38 #66 _(actually having proper Settings UI support for this is on my TO DO list)_
