### ISSUE TITLE
Enable pagent doesn't work

### ISSUE THREAD

**Issue by ahkhystrix** [SchoofsKelvin/vscode-sshfs#202]
VS Code: 1.46.0
SSH FS: 1.17.0

1. If I turn on the pageant, then it doesn’t work:
"Error while connecting to SSH FS myname: All configured authentication methods failed"

2. I see settings.json:
  
```
"sshfs.configs": [
    {
      "agent": true,
      "host": "myhost",
      "name": "myname",
      "username": "mylogin"
    }
  ],
```
3. I change the value of the option agent to pageant:

```
  "sshfs.configs": [
    {
      "agent": "pageant",
      "host": "myhost",
      "name": "myname",
      "username": "myuser"
    }
  ],
```
4. Everything is working

**Comment by SchoofsKelvin** [comment]
This seems to be a bug in the Settings UI. Instead of writing `"pageant"` when pageant is selected, it writes `true` instead.

Fixed in 26abb22, will be available in the next version after 1.17.0.
