### ISSUE TITLE
Request remote json config file

### ISSUE THREAD

**Issue by bonfiresh** [SchoofsKelvin/vscode-sshfs#204]
Hello,
on my vscode, the prev version is work fine, but after the current version update, give this err:
Thx

<img width="458" alt="2020-07-09 18 10 58" src="https://user-images.githubusercontent.com/57741172/87027385-abbfe780-c20f-11ea-94fd-4f90e751b130.png">

<img width="1331" alt="2020-07-09 17 18 40" src="https://user-images.githubusercontent.com/57741172/87023421-43bad280-c20a-11ea-8521-41ed7e94b164.png">

**Comment by SchoofsKelvin** [comment]
Which version of the extension are you running? This was indeed an issue in v1.18.0, but a few hours after its release I fixed this in v1.18.1. Perhaps this is still an issue, but I don't succeed in replicating it anymore.

**Comment by SchoofsKelvin** [comment]
After looking a bit more into it, it seems that during the whole v1.18.1 release process, the VSIX didn't actually get published to the marketplace. This results in the v1.18.0 with this issue being the last available version.

The original fix happened in deb4de03 (released in v1.18.1: e8ffe0e...1e3921c) and available in v1.18.2 that's now on the marketplace. I've double checked it's properly published this time.

**Comment by bonfiresh** [comment]
Yes!
in the newest v.1.18.2, The problem has been solved. 
grateful for your work, and this excellent extension!
