### ISSUE TITLE
Broken symlink fails to connect to remote

### ISSUE THREAD

**Issue by nathHy** [SchoofsKelvin/vscode-sshfs#21]
Was just testing out the plugin and ran into an issue.

My remote folder had a symlink in it that pointed to a non existent file.
Every time I tried connecting via the extension the workspace just said 'Could not resolve workspace folder'

Steps:
1. Create a sym link via `ln -s /not/a/path test` 
2. attempt to connect in vscode to the remote
3. Note the error exclamation mark. Hovering over says `ssh://<name>/ Can not resolve workspace folder` where name is the config name.

**Comment by SchoofsKelvin** [comment]
I've found and fixed (01b22d38) the issue, and published the patch in version 1.9.1 of the extension.
