### ISSUE TITLE
Saving file error group permissions

### ISSUE THREAD

**Issue by elelement** [SchoofsKelvin/vscode-sshfs#213]
I've been posting on issue https://github.com/SchoofsKelvin/vscode-sshfs/issues/109, which is closed, but I think I'm facing the error described on it.

What I see is that you can only edit files belonging specifically to the user you configured to login in the plugin. In a normal ssh connection, through iTerm, for example, I am able to edit files using group permissions. In other words, if the user "pi" belongs to group openhab, I'll be able to edit files belonging to that group (**664 permissions**), even if "pi" is not the propietary.
It seems to me, that this plugin is only checking that the file owner is equal to the logged in user.

Thank you for your time and your good work.

_____
_From the [original post](https://github.com/SchoofsKelvin/vscode-sshfs/issues/109#issuecomment-679934332) on #109:_

Hello. I'm facing a similar issue, if not the same. I can edit files when logged in via terminal, but not through the plugin.
This is what I'm trying to edit:
```
$ ls -lah rules/
total 24K
drwxr-xr-x  2 openhab openhab 4,0K ago 24 16:31 .
drwxr-xr-x 13 openhab openhab 4,0K may 18  2018 ..
-rw-rw-r--  1 openhab openhab 1,4K ago 25 11:46 device_4.rules
-rw-rw-r--  1 openhab openhab 1,5K ago 22 11:01 device_5.rules
-rw-rw-r--  1 openhab openhab 1,5K ago 22 10:08 device_6.rules
-rw-r--r--  1 openhab openhab  223 jun 22 14:15 readme.txt
```

I'm logging in as **"pi"** user and it belongs to the "openhab" group:
`sudo adduser pi openhab`

**Using vim or nano as "pi" allows me to edit the files** (iTerm terminal), but the plugin doesn't. Even if I use the option "open a remote SSH terminal" it doesn't work:

- Using plugin's VS Code editor:
`Failed to save 'device_4.rules': Unable to write file 'ssh://openhab-config/rules/device_4.rules' (NoPermissions (FileSystemError): ssh://openhab-config/rules/device_4.rules)`
- Using plugin's terminal option and then, using vim:
`E45: La opción 'readonly' está activada (añada "!" para forzar)  `
In the VS Code console I can see that the plugin logs in as "pi" user:
`pi@raspberrypi:/etc/openhab2$  `

There has to be something wrong with plugin. How can I enable some kind of debug log?

Thank you very much.

**Comment by SchoofsKelvin** [comment]
I've done some testing, trying to replicate this using my Ubuntu VM, but without luck.

The closest I got was more of a caching issue:
- I connected to my server (as my test user) using the extension
- I added my test user to a new group
- I created a file "test" and ran `chown root:newgroup test` and chmod'd it to `-rw-rw-r--`

The extension still uses a connection where the test user wasn't part of `newgroup`, hence it couldn't write to the file. If I started a new SSH connection _(outside vscode)_ or restarted VSCode _(closing the "stale" connection)_, I could edit the file.

I assume restarting VSCode doesn't solve your issue though? Could you run `id` in a regular ssh terminal and a terminal created by the extension, and see if they're different? At this point, the only thing I can think of is that my way of connecting somehow doesn't inherit group membership. My Ubuntu VM doesn't seem to have this issue, what OS is your server? Did you also change any ssh(d) config files on your server?

**Comment by elelement** [comment]
Thank you for your comments. **Restarting VS Code did, indeed, solve the problem**. I did the group assignments after connecting the folder to my workspace. 

Now, it works as expected. Thank you very much!
