### ISSUE TITLE
Question: will there be a port for https://open-vsx.org/ ? 

### ISSUE THREAD

**Issue by nexxtnit** [SchoofsKelvin/vscode-sshfs#218]
Hello
I just wanted to ask if there will be a port to a https://open-vsx.org/ Application. There are no ssh packages on the marketplace yet and sshfs seems nice. 
Thanks for the effort and time, if you need help please let me know. I am a beginner but if there is time I would gladly learn how to port it and contribute.
greetings

**Comment by SchoofsKelvin** [comment]
I'll have to look a bit into it. At first sight, it seems like I won't have to make any modifications to the extension.

Which application do you want this extension for? It'd be handy for me so I can test whether publishing was succesful.

**Comment by nexxtnit** [comment]
Dear @SchoofsKelvin  thank you very much for the answer. Like I said before I am not totally sure myself how to create the open-vsx application. The documentation about it is here though: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions 
The extension is for https://vscodium.com/ the open source version of vscode without microsoft telemetry. The extension on open-vsx will also be available for the https://theia-ide.org/ forks I think. 
I mean it is still possible to install your extension on vscode with manually downloading it from the windows marketplace. It would just be much easier to get it from open-vsx because then I can use the extensions menu in vscodium which works like the extensions menu in vscode.
Overall I really like your extension though, works good and is very usefull :)

**Comment by cheese** [comment]
Tested with vscodium from open vsx at https://open-vsx.org/extension/Kelvin/vscode-sshfs . This issue can be closed.
