### ISSUE TITLE
PuTTY & remote prompt for 1TP: Pageant not running error?

### ISSUE THREAD

**Issue by adamlopuch** [SchoofsKelvin/vscode-sshfs#22]
Using an existing PuTTY session and the "complete" configuration in SSH FS (very nifty!).

Remote server is set to prompt me for a one-time password (from a soft token).  This is separate from a password... changes every 60 seconds.

When I connect: SSH FS throws "Error while connecting... Pageant is not running", however it does show Visual Studio Code prompt for the one-time password.  When I enter the 1TP, though, it doesn't connect.

Any thoughts on ways around this?

Added to my User Settings:
```
    "sshfs.configs": [
      {
          // With PuTTY, this can be a complete configuration (with / as root)
          "name": "me_on_remoteserver",
          "putty": "PUTTY SESSION NAME HERE",
      }
    ]
```

On connecting, error about Pageant not running:
![image](https://user-images.githubusercontent.com/4812285/41978321-97ec3f98-79ef-11e8-8ed3-670209b5abe0.png)

GUI prompts me for my one-time password as expected... but after entering, connection still not made
![image](https://user-images.githubusercontent.com/4812285/41978352-ab7e3106-79ef-11e8-85a0-e7b99be2d96d.png)

**Comment by SchoofsKelvin** [comment]
Do you only have to enter the PASSCODE to authenticate yourself? Or is it on top of a password?

Do you (also) need to authenticate using a private key, and if so, is Pageant running with the key loaded?

You could try changing your PuTTY session to not use an agent *(Connection > SSH > Auth: "Attempt authentication using Pageant")*. If that works, I'll add `"agent": false` to allow (forcefully) disabling the use of Pageant.

**Comment by adamlopuch** [comment]
Nice -- the PuTTY session configuration resolved the issue.  Love the PuTTY wizardry!

**Resolution steps:**
No change to the SSH FS configuration.  I only unchecked the 'Attempt authentication using Pageant' PuTTY option (and saved session / reloaded).  The PuTTY session still works through PuTTY terminal, and now works perfectly with SSH FS.

Screenshot of happy green SSH FS connection:
![image](https://user-images.githubusercontent.com/4812285/41983286-a1c3a2b6-79fb-11e8-8388-37e5cdcbb35f.png)

**Notes on my configuration**
Yes, it might be useful to have a future feature for `"agent": false` (for when PuTTY is not used).

In my environment, username and the one-time password ("PASSCODE") are only authentication criteria transmitted: no password, no private key exchanges.  This is a private network; access permissions are handled earlier in the connection process.
