### ISSUE TITLE
Support for opening clicked paths in terminal

### ISSUE THREAD

**Issue by jraygauthier** [SchoofsKelvin/vscode-sshfs#222]
Would it be possible for the extension to propose opening the file in the ssh fs folder when user clicks on a path in the terminal (e.g.: when error occurs, call stacks, etc)?

This would be a great time saver.

**Comment by SchoofsKelvin** [comment]
I'll look into this when I have more time.

Note to self: `TerminalLinkProvider`

**Comment by SchoofsKelvin** [comment]
Added in aa17321, will be live in v1.19.1 of the extension.

Currently only supports absolute paths that are reachable of your configured root. E.g. if your config specifies `~/project` as `Root`, then absolute paths will only work if they start with `/home/USER/project`, `/root/project`, or whatever `~/project` resolves to.

Future tasks:
- Make absolute paths outside `Root` work _(requires something like `ssh://<name>:root/...`)
- Make relative paths work **(probably not gonna happen soon, would need `cd` detection for the shell)**
_(alternatively open the "quick file search picker" like VSCode does, but we lack a search provider #2)_
