### ISSUE TITLE
Password prompt does not grab focus

### ISSUE THREAD

**Issue by mablanchard** [SchoofsKelvin/vscode-sshfs#223]
Very minor but still: right clicking on a SSH FS configuration from the side bar and selecting _Connect as Workspace Folder_, the password box prompts but the password entry widget does not grab focus (which thus require an extra click in the entry to set it...). Would be nice for the password entry to always grab focus on exposition I think (as most likely the user will want to type in his password at that point).

**Comment by SchoofsKelvin** [comment]
Similar to #221, this is something I can't change. The extension uses the VSCode API to prompt the user for input, but it's VSCode itself rendering the UI, handling focus, ...

You can bring it up [here](https://github.com/microsoft/vscode/issues), but currently there is no quick fix for this it seems.
