### ISSUE TITLE
Extremly slow since few weeks

### ISSUE THREAD

**Issue by fanelligroup** [SchoofsKelvin/vscode-sshfs#226]
Hello,
I have a strange problem. I was using this extension without any problem until a few weeks ago. Now it has become usable because, while establishing the connection correctly, every file opening, folder opening, saving is very slow (we are talking about several minutes). The hosting says everything is OK from their front and my connection is very fast.

**Comment by SchoofsKelvin** [comment]
If possible, can you check if this happens when using an older VSCode version, from before those few weeks? The extension hasn't had any updates for more than just a few weeks.

**Comment by fanelligroup** [comment]
I downgraded to September version and now all is working fine.

**Comment by SchoofsKelvin** [comment]
I'll look into it, but it'll be tricky. The extension behaves just fine for me (VSCode 1.52.0), and even if I had the issue, it'd be tricky to find a change in the VSCode codebase that could cause this.

**Comment by fanelligroup** [comment]
Ok thanks! For now I'll use the old version.

**Comment by SchoofsKelvin** [comment]
Might be related to microsoft/vscode#74517, although that was quite a while ago and apparently(?) solved.

September version would be VSCode 1.50.0, and the issue happens in both 1.51.0 and 1.52.0?

**Comment by fanelligroup** [comment]
Version > 1.50.1 have that bug

**Comment by SchoofsKelvin** [comment]
Reopen if this is issue still applies.
