### ISSUE TITLE
SSH File System is missing from explorer after updating vscode

### ISSUE THREAD

**Issue by arunandroapps** [SchoofsKelvin/vscode-sshfs#227]
SSH File System is missing from explorer after updating vscode.

![Screenshot 2020-12-17 at 2 04 51 PM](https://user-images.githubusercontent.com/22675494/102463233-d80a4a80-4070-11eb-9f2d-438ed50dffad.png)

**Comment by SchoofsKelvin** [comment]
On the left, the second to last icon, is a new `SSH FS` view, added in v1.19.0. It lists all the configurations, along with all the connections and a bunch of buttons and right-click menus to manage them:
![image](https://user-images.githubusercontent.com/14597409/102493098-f2ddbe80-4072-11eb-82ab-9ca368891d21.png)

You can of course drag the `Configurations` pane to the Explorer view to replicate the old look in a way:
![image](https://user-images.githubusercontent.com/14597409/102493225-2a4c6b00-4073-11eb-8b56-baf9961e7224.png)

**Comment by GitMensch** [comment]
I guess this issue can be closed?
