### ISSUE TITLE
Open remote SSH Terminal Doesn't Work in Latest Update

### ISSUE THREAD

**Issue by thekendog** [SchoofsKelvin/vscode-sshfs#228]
Whatever update came out yesterday broke the functionality where I could right click on a folder in the file explorer and open an SSH terminal there.  Now, I get a dropdown prompt that does nothing when I click on it.

**Comment by SchoofsKelvin** [comment]
Fixed in b0155c5 (and skipping the prompt in d66e278), will be live in v1.19.1 of the extension.
