### ISSUE TITLE
New UI Buttons aren't doing anything

### ISSUE THREAD

**Issue by aceamarco** [SchoofsKelvin/vscode-sshfs#229]
Hi,

I'm trying to use the extension after the new UI update but whenever I click any of the new buttons nothing happens. I can't figure out how to open my connection as a new workspace folder. When I click the folder icon I get this prompt at the bottom of my VScode window but nothing pops up in the open folders section.
![Screen Shot 2020-12-20 at 3 32 30 PM](https://user-images.githubusercontent.com/39501599/102723774-94197e80-42d8-11eb-813c-0ead3f2d5620.png)

Thank you in advance — I've loved using this extension!

**Comment by SchoofsKelvin** [comment]
Which version of the extension and VSCode are you using? Does this happen every time?

Can you post the `SSH FS` log? It is available under `Output > SSH FS`. While it should censor passwords/passphrases, I recommend checking it for (other) sensitive data first.

That message means clicking the `Add as Workspace folder` actually did what it's supposed to do. Might be related to #150, although that shouldn't _(as far as I know)_ prevent e.g. `Open remote SSH terminal` from breaking.
