### ISSUE TITLE
Problems with sshfs tasks and agent-forwarding

### ISSUE THREAD

**Issue by wow-solution** [SchoofsKelvin/vscode-sshfs#233]
Hi and thx for your great vscode extension!

My ssh-shell task gives me the following output after I run it:
(I'm not sure if i have to put into host the IP or the hostname from sshfs.configs but tried both and neither worked.)

```
Error: The ssh-shell task detection didn't contribute a task for the following configuration:

{
    "label": "test",
    "type": "ssh-shell",
    "host": "xxx.xxx.xxx.xxx",
    "command": "echo: test",
    "problemMatcher": []
}
The task will be ignored.
```

The second problem is, that the agent forwarding don't work in the sshfs shell. 

`Permission denied (publickey,keyboard-interactive).`

My ssh config I have this configuration and this works for the standard terminal and with the sftp extension terminal:

```
Host *
  ForwardAgent yes
  IdentityFile ~/.ssh/id_rsa
```

Best regards

Wolfgang Wagner

**Comment by SchoofsKelvin** [comment]
For the task, use the name of your configuration.

The extension currently doesn't support reading `.ssh/config` _(see #107)_.

As for agent forwarding, there is a workaround (#93) for it:
- Open your `settings.json` file _or wherever the SSH FS configs are stored, by default it's the `sshfs.configs` field in your VSCode `settings.json`
- Add `"agentForward": true` to the configs of your choice

That should in theory enable forwarding.
