### ISSUE TITLE
key exchange algorithm - settings

### ISSUE THREAD

**Issue by Hentze0808** [SchoofsKelvin/vscode-sshfs#236]
Hi

I am having problems with the add on for VS code. It promts for user and then fails with this message.:
Couldn't start a terminal for mymi: Handshake failed: no matching key exchange algorithm

Is there any fix for this..? 

Maybe somewhere where I can add the Algorithms..?

Thanks in andvance.!
/Ragnar

**Comment by SchoofsKelvin** [comment]
Can you post the `SSH FS` log? It is available under `Output > SSH FS`. While it should censor passwords/passphrases, I recommend checking it for (other) sensitive data first.

Which key algorithms does your server support? I use an external module called [ssh2](https://www.npmjs.com/package/ssh2) to handle the actual SSH connection _(apart from some proxy stuff)_, which might not support your key algorithm.

**Comment by Hentze0808** [comment]
Sure!
I use this with other SSH configs.
Ciphers 3des-cbc
KexAlgorithms +diffie-hellman-group1-sha1

And log says:
[INFO]    Command received to open a terminal for FileSystemConfig(mymi)
[INFO]    [createConnection(mymi,config)] Creating a new connection for 'mymi'
[INFO]    Calculating actual config
[DEBUG]   	Final configuration:
{
    "name": "mymi",
    "host": "SECRET",
    "_location": 2,
    "_locations": [
        2
    ],
    "_calculated": {
        "name": "mymi",
        "host": "SECRET",
        "_location": 2,
        "_locations": [
            2
        ]
    },
    "username": "root"
}
[INFO]    [createSocket(mymi)] Creating socket
[DEBUG]   [createSocket(mymi)] Connecting to SECRET:22
[INFO]    [createSSH(mymi)] Creating SSH session over the opened socket
[ERROR]   [createSSH(mymi)] Handshake failed: no matching key exchange algorithm
Logged at:
	at T.<anonymous> (c:\Users\RAHEN\.vscode\extensions\kelvin.vscode-sshfs-1.19.1\dist\2.extension.js:1:9079)
	at T.emit (events.js:223:5)
	at ae.<anonymous> (c:\Users\RAHEN\.vscode\extensions\kelvin.vscode-sshfs-1.19.1\dist\0.extension.js:717:121)
	at ae.emit (events.js:228:7)
	at c:\Users\RAHEN\.vscode\extensions\kelvin.vscode-sshfs-1.19.1\dist\0.extension.js:4945:179
Reported from createSSH(mymi)

If more info is needed, I will give what I know.

**Comment by SchoofsKelvin** [comment]
According to [this](https://www.npmjs.com/package/ssh2-streams#ssh2stream-methods), these two are supported, although not enabled by default.

You should be able to enable them by opening your `settings.json` _(wherever your SSH FS config is stored, in your case it seems to be your workspace file)_ and add these two fields:
```json
"sshfs.configs": [
        {
            "name": "mymi",
            "algorithms": {
                "kex": ["diffie-hellman-group1-sha1"],
                "cipher": ["3des-cbc"]
            }
        }
]
```
You might have to add `serverHostKey`, `hmac` and `compress` if the underlying library I use doesn't like you only overwriting `kex` and `cipher`.
