### ISSUE TITLE
fish shell

### ISSUE THREAD

**Issue by Mirzaev228** [SchoofsKelvin/vscode-sshfs#237]
hello. trying to connect to a terminal:
under bash, of course, everything is fine

![123](https://imageup.ru/img130/3697722/2021-01-19_17-29-01.png)

**Comment by SchoofsKelvin** [comment]
I've never heard of a fish shell before, seems to be one of the more exotic ones? Could you try changing your config's `Terminal command` to `eval SHELL`  or whichever way fish allows starting your (main) shell? Could also just be `/bin/fish` or such:
![image](https://user-images.githubusercontent.com/14597409/105093590-493f8200-5aa3-11eb-8b76-bc0ce07c10da.png)

**Comment by Mirzaev228** [comment]
thank you

![изображение](https://user-images.githubusercontent.com/21334019/106372235-8405bc00-63b9-11eb-9f3b-2c71fdb7b07b.png)
