### ISSUE TITLE
Handshake failed: signature verification failed

### ISSUE THREAD

**Issue by jalbertodin** [SchoofsKelvin/vscode-sshfs#238]
When trying to connect to a solaris remote host: Error while connecting to SSH FS solarisrhino: Handshake failed: signature verification failed

I can access the host using putty without any problem

Any suggestion or debug?

**Comment by SchoofsKelvin** [comment]
Can you post the `SSH FS` log? It is available under `Output > SSH FS`. While it should censor passwords/passphrases, I recommend checking it for (other) sensitive data first.

Which algorithms/ciphers does your server allow/support? This might be similar to #236.
