### ISSUE TITLE
Update tags section in Marketplace

### ISSUE THREAD

**Issue by integeruser** [SchoofsKelvin/vscode-sshfs#25]
Hello,

not an issue, but maybe you'd want to update the tags section in [the page of the extension in the Marketplace](https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs); this extension is exactly what I needed but had some troubles in finding it.

**Comment by SchoofsKelvin** [comment]
I'll add some tags later on. If you have some good tags in mind, feel free to post them here or open a pull request.
