### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by kedarotta** [SchoofsKelvin/vscode-sshfs#256]

**Comment by SchoofsKelvin** [comment]
Can you post the `SSH FS` log? It is available under `Output > SSH FS`. While it should censor passwords/passphrases, I recommend checking it for (other) sensitive data first.

At first glance, the `All configured authentication methods failed` makes it seem as if you misconfigured the password/agent/..., used the wrong key, don't have your agent selected and running with the right key, ...

**Comment by kedarotta** [comment]
The issue got resolved by clearing the catche. Thanks :)
