### ISSUE TITLE
Error if username contains dash - 

### ISSUE THREAD

**Issue by MichlMann** [SchoofsKelvin/vscode-sshfs#264]
example:

ssh-123456-username@domain.tld:22/asdf/asdsf

**Comment by SchoofsKelvin** [comment]
Quick glance makes it likely to be caused by this regex:
https://github.com/SchoofsKelvin/vscode-sshfs/blob/94f2c37ab0082da4370a0c10a176a66f9bb4bfc1/src/fileSystemConfig.ts#L136

**Comment by SchoofsKelvin** [comment]
Fixed this issue (f05108a) which will be available in v1.20.2 of the extension, which will be released in about 10 minutes or so.
