### ISSUE TITLE
agentForward activation

### ISSUE THREAD

**Issue by amoire** [SchoofsKelvin/vscode-sshfs#265]
Hello,

Is it possible to activate agentForward when an agent is configured ?

On connect.ts file, createSSH function (see attached file) :
      if (config.agent) {
        finalConfig.agentForward = true;
      }
Best regards

[connect.zip](https://github.com/SchoofsKelvin/vscode-sshfs/files/6663059/connect.zip)

**Comment by SchoofsKelvin** [comment]
Enabling it by forward seems a bit of a security issue. You can modify the config's JSON file (VSCode's User Settings' `settings.json` file) and manually add an `"agentForward": true` field to your config.

I could add a checkbox in the Settings UI for this though.

**Comment by SchoofsKelvin** [comment]
Added a checkbox in the settings UI:
![image](https://user-images.githubusercontent.com/14597409/123657143-d34cfd00-d830-11eb-9f45-4658d47db03f.png)

This change (d167ac8) will be available in v1.20.2 of the extension, which will be released in about 10 minutes or so.
