### ISSUE TITLE
connecting to the the proxy: An invalid destination host was provided.

### ISSUE THREAD

**Issue by sakurarain99** [SchoofsKelvin/vscode-sshfs#266]
This error always occurs when using proxy to connect. Here is the proxy configuration
`
{
            "name": "name",
            "host": "host",
            "username": "username",
            "password": "password",
            "proxy": {
                "host": "127.0.0.1",
                "port": 3279,
                "type": "socks5"
            }
        }

`

**Comment by sakurarain99** [comment]
The proxy can be used in "putty" and successfully connected

**Comment by SchoofsKelvin** [comment]
This issue would be easier to solve with debug logs, so please follow these steps:
- Add `DEBUG_SSH2` to the `sshfs.flags` array in VS Code's User Settings (settings.json)
    e.g. `"sshfs.flags": ["DEBUG_SSH2"]`
- If you already have a connection open, close it completely (or even reload the window)
- Go to `Output > SSH FS` and copy the log from there after replicating your bug
-  While it should censor passwords/passphrases, I recommend checking it for (other) sensitive data first.
    _(especially since `DEBUG_SSH2` activates some internal logging, which is less likely to be censored)_

**Comment by sakurarain99** [comment]
This is the connection log. The prompt is undefined. What does undefined mean?

[INFO]    Creating socks proxy connection for 192.168.24.38
[DEBUG]   Resolved hostname "127.0.0.1" to: 127.0.0.1
[DEBUG]   	Connecting to 192.168.24.38:undefined over socks5 proxy at 127.0.0.1:3279

**Comment by SchoofsKelvin** [comment]
Seems like your config doesn't specify a port. While the SSH part is smart enough to default to 22, it seems like the proxy system isn't. Fixed it in a41c435, which will be live in v1.21.0 of the extension, about to be released in a few minutes.

**Comment by sakurarain99** [comment]
OK, thank you. Problems and solutions
