### ISSUE TITLE
Can't active php anymore

### ISSUE THREAD

**Issue by AlexandreGagner** [SchoofsKelvin/vscode-sshfs#272]
Hi,
Since update, i can work with php file anymore, php extension is like "disable because of virtual workspace" i don't understand why.

Anyone have idea to get it work ? Maybe it's not about sshfs extension.

Thx

**Comment by SchoofsKelvin** [comment]
This is probably the PHP extension's version of  microsoft/vscode#123115. Although I assume the extension didn't (100%) work with virtual workspaces anyway, they probably now actually marked their extension as such.

If it's for intensive development will full extension support, I suggest using VS Code's [Remote SSH](https://code.visualstudio.com/docs/remote/ssh).
