### ISSUE TITLE
Tab Filaname Label

### ISSUE THREAD

**Issue by Leboubou111** [SchoofsKelvin/vscode-sshfs#278]
Recently, I have `(SSH FS)` displayed after the file name in the tab navigation.
How I can disable this one ?

Exemple : 

![image](https://user-images.githubusercontent.com/8314926/128208570-65612cc3-48f3-48f8-a643-cc30e155154d.png)

**Comment by Leboubou111** [comment]
I've tried with `"workbench.editor.labelFormat"` and `"window.title"`

**Comment by SchoofsKelvin** [comment]
I'll look into this later today. I think I know what's causing it, but need to double-check whether it isn't a new VS Code feature I can't control.

**Comment by Leboubou111** [comment]
Thanks @SchoofsKelvin 👍

**Comment by SchoofsKelvin** [comment]
Fixed the issue. Will be available in a little bit in version v1.21.2 of the extension.

**Comment by Leboubou111** [comment]
Work fine. Thanks ;-)
