### ISSUE TITLE
Locks up when trying to save with python vscode extension running

### ISSUE THREAD

**Issue by mikessut** [SchoofsKelvin/vscode-sshfs#281]
When the python extension is enabled, vscode locks up when trying to save.  I can work around by disabling the python extension.

Maybe it's an issue with the python extension as it tries to lint?

**Comment by SchoofsKelvin** [comment]
That does sound like an issue on their end. As far as I know, the Python extension doesn't support remote filesystems (#42, #45, ...) although it's the first time someone complained about it actually causing VS Code to lock up. I suggest checking for known issues on their end and/or reporting this.

_Should they end up figuring out this extension is somehow (part of) the cause, feel free to reopen this issue._
