### ISSUE TITLE
Config location on Windows?

### ISSUE THREAD

**Issue by MostHated** [SchoofsKelvin/vscode-sshfs#284]
Hey there,
    I am using this plugin on my work pc which uses Windows 10, and I wanted to migrate all my settings to a VM, but unfortunately, I can't seem to locate where the config file with the servers info I had set up prior is stored. Is this something I can copy over to another pc?

Thanks,
-MH

**Comment by SchoofsKelvin** [comment]
Whenever you create a config, you get a dropdown to pick where it's stored. By default this is "Global Settings", which is actually the `ssh.configs` key in your User Settings _(run the command `Preferences: Open Settings (JSON)`, which should open `%APPDATA%\Code\User\settings.json` for me, but depends on how you installed VS Code)_.

It's also possible to be stored in workspace configs and dedicated config files, but it's highly unlikely you're using those last two.
