### ISSUE TITLE
Terminal colors dont work & show weird characters (fish shell)

### ISSUE THREAD

**Issue by tennox** [SchoofsKelvin/vscode-sshfs#299]
Have a fresh raspbian/debian with fish shell:
![Screenshot from 2021-10-15 15-26-31](https://user-images.githubusercontent.com/2084639/137494558-8df482fe-1ab7-4ceb-a156-e45a4df5c90d.png)

**Comment by SchoofsKelvin** [comment]
What does `echo $TERM` output, and is this different from when you're connecting to your server outside VS Code?

Did you also add `-CHECK_HOME` to your flags? Using `fish` as login shell _should_ error right now about not finding the home directory (`fish` doesn't support backticks for command substitution, which I use for this). I'm actually working on a way to support a lot more shells, which will help with this. _This is separate from the weird characters/colors though._

**Comment by tennox** [comment]
Yep, inside VSCodium it's `vt100` and the suggestion of @psolyca fixed the issue :+1: 

Thanks also for the tip about `"sshfs.flags": ["-CHECK_HOME"]` :+1:
it removes the warning I had to ignore each time :yum:

**Comment by SchoofsKelvin** [comment]
Released in [v1.24.0](https://github.com/SchoofsKelvin/vscode-sshfs/releases/tag/v1.24.0) of the extension.
