### ISSUE TITLE
Running a code file in Remote SSH Terminal directly from the menu

### ISSUE THREAD

**Issue by candancaner** [SchoofsKelvin/vscode-sshfs#307]
Is there a way to run a code file (specifically a Python code for example), directly from the file explorer? I have noticed that we can open a remote terminal within folders, but not in the file level. It would be great to add a new button such as "Run in Remote Terminal" to the menu.

**Comment by SchoofsKelvin** [comment]
The extension adds a new `ssh-shell` task type you can use:
![Screenshot](https://github.com/SchoofsKelvin/vscode-sshfs/raw/master/media/shell-tasks.png)
You can also use variables such as `${remoteFile}` and `${remoteWorkspaceFolder}` (basically `${file}` and `${workspaceFolder}` but for `ssh://` URIs) to target the currently opened file. See #232 for more info about that.
