### ISSUE TITLE
After a VS Code Update SSHFS is disabled

### ISSUE THREAD

**Issue by 1000dinge** [SchoofsKelvin/vscode-sshfs#308]
Hi, after a recent update VS Code has disabled the SSHFS-Extension until i install vscode-remote. As i remember that extension was not neccessary until now. I'm not a daily user of VS Code, so its possible i missed something, but as vscode-remote install things on the remote system i dont want to use that extension.

Is it possible to us SSHFS without enable vscode-remote?

**Comment by psolyca** [comment]
I am using VSCodium and vscode-remote is not needed.
I am with SSH FS 1.24.0.

**Comment by SchoofsKelvin** [comment]
Which version of VS Code and the extension have you installed? I just tested with VS Code 1.62.0 and version 1.24.0 of the extension and it works fine for me without any `vscode-remote`-related extension installed.

**Comment by 1000dinge** [comment]
After updating to VSCode 1.62.0 (MacOs 11.6) thru Autoupdate SHFS (latest) and the MSSQL-Extension were disabled because i had to install and use VSCode Server. I used VSCode last week and all works fine, and i don't updated MacOs or something since. As you guys have no problems with that, please close this ticket. I'll give VSCodium a shot or restore VSCode in the last version from backup to understand what happend. Thank you guys.

**Comment by 1000dinge** [comment]
I reverted to 1.59.1 from Time Machine and disabled AutoUpdate. It works immediately. Strange.
