### ISSUE TITLE
Copy Path without ssh://

### ISSUE THREAD

**Issue by NightProgramming** [SchoofsKelvin/vscode-sshfs#318]
When using the Copy Path feature of the workspace something like `ssh://myuser/home` is added to the clipboard. When using paths in the SSH terminal or with the "Open file" feature (ctrl + o) paths like `/home` are used (no `ssh://`).

I don't know if it's possible but maybe it would be nice if "Copy Path" would directly give the path without `ssh://`?

**Comment by SchoofsKelvin** [comment]
That context-menu item is something built-in into VS Code, the extension doesn't add it nor can it influence it. As for `Ctrl+o` not accepting proper URIs, that's also not something I can change. But as part of #316, I might be able to make `Ctrl+p` support `ssh://` URIs, depending on how much I can influence VS Code regarding that.
