### ISSUE TITLE
Run Build Task command doesn't work with added remote folder into workspace

### ISSUE THREAD

**Issue by amigo421** [SchoofsKelvin/vscode-sshfs#321]
I'm using the extensions on Windows  with latest stable vscode and c++ extension.
as soon as I add (using SSH-FS) remote folder to workspace , the command Tasks: Run Build Task shows me "Fetching Build Configurations" and never stops. Removing remote folder solves the problem

**Comment by SchoofsKelvin** [comment]
Does this only happen with the C++ extension enabled? If so, that seems to be an issue on their end, they probably don't support remote filesystems (the FileSystemProvider extension API this extension uses) and get stuck trying to read from "it" (most likely trying to read from the local filesystem instead). Check their issues for something like this, or make a new issue. If it's actually something my extension is handling wrong, feel free to reopen this issue.

**Comment by amigo421** [comment]
okay, thank you, I'll discuss/raise this in their repository
