### ISSUE TITLE
Is there a way to specify options for the ssh command run to open the terminal?

### ISSUE THREAD

**Issue by keshprad** [SchoofsKelvin/vscode-sshfs#325]
I basically want to open the terminal with the following and I’m not sure how to do  this.
```bash
ssh -Y user@domain.com
```

**Comment by SchoofsKelvin** [comment]
No, the extension doesn't use the `ssh` executable, so X11 forwarding is a feature I'd have to manually add to the extension. It's something I can look into adding though, although not soon. For now you'll have to run `ssh -Y` separately to get X11 forwarding.
