### ISSUE TITLE
SSH Connection always reloads

### ISSUE THREAD

**Issue by jun2mar** [SchoofsKelvin/vscode-sshfs#333]
Hello may I ask if it is normal.
Every time I get out of the VS Code window and go back SSH FS connect gets reload all from main down to the focused file folder.

**Comment by SchoofsKelvin** [comment]
What do you mean with "get out of the VS Code window", as in close the window? Or lose focus?

By "reload all from main down to the focused file folder", you mean the explorer pane refreshes I assume? If that's the case, that's an issue with VS Code.

**Comment by jun2mar** [comment]
> 



> What do you mean with "get out of the VS Code window", as in close the window? Or lose focus?
> 
> By "reload all from main down to the focused file folder", you mean the explorer pane refreshes I assume? If that's the case, that's an issue with VS Code.

Yes when lose focus on VS Code window, SSH FS refreshes when I return on VS Code window,
I see, so this is VS Code issue. Thanks for the reply.
