### ISSUE TITLE
Opening files via commandline in 2022

### ISSUE THREAD

**Issue by luckman212** [SchoofsKelvin/vscode-sshfs#335]
_Originally posted by @SchoofsKelvin in https://github.com/SchoofsKelvin/vscode-sshfs/issues/160#issuecomment-655045830_

> While directly using `code ssh://...` still isn't supported, `code --file-uri ssh://a/file` and `code --folder-uri ssh://a/folder` are now.

**Comment by luckman212** [comment]
I want to first thank you for this very useful extension! It's really coming in handy.

I am wanting to use the commandline / URI scheme to open some remote files, but am not having any luck. I tried e.g.

```shell
code --file-uri ssh://r1/usr/local/
```
where `r1` is the name of one of my configs. But it did nothing. Code opens, but the workspace was empty. I scoured the app code and found that there is another undocumented commandline paramter `--folder-uri` which seems to work...

```shell
code --folder-uri ssh://r1/
```
but if I want to automate opening up a session to a particular host with a few files & folders visible, I am not sure how to do it, or if it's even possible...

**Comment by SchoofsKelvin** [comment]
My extension just makes it that inside VS Code `ssh://<host>/<path>` URIs are handled properly, i.e. looking for an existing config for `<host>` or making one on the fly if it looks like `username@host` _(this last bit might not be released yet and just be something I have on a feature branch, not sure)_.

It doesn't look like VS Code improved their CLI to accept any URI, e.g. `code ssh://<host>/<path>/`. Sadly enough not something I can fix but an improvement that VS Code has to add.
