### ISSUE TITLE
Support for platform specific agent?

### ISSUE THREAD

**Issue by Duncank** [SchoofsKelvin/vscode-sshfs#339]
I'm authenticating via `agent: pageant` on Windows, but need to use `agent: $SSH_AUTH_SOCK` on Mac. Since VSCode doesn't support platform specific settings-sync, I'm constantly changing this manually.

Could this extension support a multi-platform solution, or has anyone thought of a way of doing this already?

**Comment by Duncank** [comment]
I've looked around in the code for this extension and noticed that the `agent` is matched against my environment variables if one exists with the same name.  

So I've created a workaround by:
* using `agent: "$SSH_AUTH_SOCK"` for every connection (this works on Mac)
* creating an (user)-environment variable in Windows called `SSH_AUTH_SOCK` with a value of `pageant`.

Feel free to close this issue as this resolves my use case; of course a native solution would be welcome as well.

**Comment by SchoofsKelvin** [comment]
That's indeed one way to resolve your issue.

I'll see about supporting a small subset of [bash shell parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) to all fields that support environment variables. In that case, `${SSH_AUTH_SOCK:-pageant}` would resolve to `pageant` if `$SSH_AUTH_SOCK` is empty or unset. _Looking at [this](https://stackoverflow.com/a/12691027/14274597), you could then technically also add a ternary operation on some `$PLATFORM` variable, but I might add a simpler way to do that._ That or a form of angular expressions where `$VAR` are `const` environment variables, I'll see. Not a priority right now though.
