### ISSUE TITLE
Characters are displayed with an offset for the settings

### ISSUE THREAD

**Issue by lucasoeth** [SchoofsKelvin/vscode-sshfs#347]
![Screen Shot 2022-06-27 at 1 17 34 PM](https://user-images.githubusercontent.com/43838158/175929596-d05ea171-dd8d-42a8-871f-da361e661837.png)

Here is a snippet of my screen. When I copy and paste the wrongly displayed text into a text file, it is the correct text. Hence, there is some kind of character shift added to the text that is displayed. 

Initially, I assumed that this problem is not extension related but something global. I have not been able to find helpful results when googling. This is why I decided to post it here.

I am using an M1 MacBook, which could also be somehow related to this. Any pointers appreciated :)

**Comment by SchoofsKelvin** [comment]
I suggest creating an issue on VS Code's [issue tracker](https://github.com/microsoft/vscode/issues). I had a look myself and couldn't find anything that seems like your issue, only microsoft/vscode/issues#146381 seems remotely close (although that's not the weird "one font is shifted by two characters" issue you).

Some "debug" information regarding those text labels in your screenshot:
The `body` has `font-family: sans-serif`, which should be the font displayed here
- The `Label` is `font-size: 110%; font-weight: 600` where the `font-weight` might result in it using a different non-broken bold version of supposedly `sans-serif`
- The `Qrvkqpcn` (should be `Optional`) right of ^ is `opacity: 0.75`
- The small text under the above labels is `opacity: 0.75`

The two wrongly rendered text `div`s have two things in common, namely not being bold (no `font-weight`) and having an `opacity` different from 1.

You can use the `Developer: Open Webview Developer Tools` command to double-check all of that. I'm pretty confident it won't be an issue in the DOM/CSS, but the actual rendering of it done by VS Code.
