### ISSUE TITLE
No search provider registered for scheme: ssh 

### ISSUE THREAD

**Issue by JeremyWuuuuu** [SchoofsKelvin/vscode-sshfs#35]
When I tried to search a file via VSCode's `Command + P`, this error keeps jumping out and seems like there's no way to open a remote file via this command.
![image](https://user-images.githubusercontent.com/15975785/44563842-afb8fc80-a792-11e8-90f4-7db6241f77b3.png)

**Comment by jackalcooper** [comment]
This is a pain point when using vscode-sshfs. It would be perfect if it supports searching files.

**Comment by JeremyWuuuuu** [comment]
Yes, so I gave up on this.. I hope one day vscode team could support this kind of strategy.

**Comment by malonnnn** [comment]
So this won't be addressed?

Guess I'm not using this extension
