### ISSUE TITLE
SSH FS won't connect to my server that uses publickey **and** password authentication.

### ISSUE THREAD

**Issue by reticle5** [SchoofsKelvin/vscode-sshfs#350]
Standard SSH client works fine. But no luck with SSH FS. Looking at the logs, looks like SSH2 might manage the exchange incorrectly. But I'm new to all of this, so here's my issue, logged.

[debug.log](https://github.com/SchoofsKelvin/vscode-sshfs/files/9152572/debug.log)

**Comment by hungry-bogart** [comment]
Having similar issues. It continues to ask me for a password, even though I only use SSH for the server I'm using. If I try to add an SSH key it says all authentication methods have failed. I'm using VSCodium for this. Hope you find an answer.
