### ISSUE TITLE
Navigate out of the "Root" subtree when using a configuration as workspace folder

### ISSUE THREAD

**Issue by CMR-DEV** [SchoofsKelvin/vscode-sshfs#353]
Many thanks for this awesome plugin!

When I use the "Root" setting in a configuration (say `/home/somebody`) it is obviously possible to navigate to a parent or other location by `cd ..` or `cd /etc/whatsoever` as long as this connection is opened in terminal. However, when the configuration is used as workspace folder the file tree intentionally for sure becomes limited to this "Root" directory with no chance to navigate to a parent location. Of course one could create and follow a symlink `ln -s / root` or a bind mount on the host system in order to access the file system root, but that is no very intuitive in my opinion.

**Question is**: Is it possible to somehow access parent locations when a connection is used as a workspace folder despite using this "Root" setting without creating a symlink? Otherwise, I'd love to have a setting like "Only expand file tree to this root location when used as a workspace folder" under the "Root" setting. Could be a single checkbox etc.

**Comment by SchoofsKelvin** [comment]
The only thing the `Root` does is specifying the _default_ path used for creating the terminal (unless it's done by right-clicking a directory in the Explorer pane and selecting "Open remote SSH terminal") and the `SSH FS: Add as Workspace Folder` command.

In practice this means that when you add the workspace folder using the command, it actually adds `ssh://<config-name>/home/somebody` as workspace folder. You can change this by using `Preferences: Open Workspace Settings (JSON)` and changing the URI (you'll see which one) to something else.

_As a nice bonus, nothing prevents you from adding multiple workspace folders for the same SSH connection._
