### ISSUE TITLE
Default edit file permissions

### ISSUE THREAD

**Issue by rishi-dhar** [SchoofsKelvin/vscode-sshfs#355]
Noticed that when I edit a file on remote server via the extension the file permissions change from rw-r--r-- (644) to rw------- (600). How do I avoid that? Would like the file permissions to stay the same after an edit.

**Comment by SchoofsKelvin** [comment]
When editing a file, the extension first `stat`'s the file to get its current permissions and reuses that. As a side note, in the Settings UI you can change the default file mode for _new_ files, but this defaults to `rw-rw-r--` so I'm not sure where your 600 comes from. If this is still an issue, could you reopen the issue with more information?
