### ISSUE TITLE
An option to disable the watch of files and directories

### ISSUE THREAD

**Issue by set-killer** [SchoofsKelvin/vscode-sshfs#360]
Hello,

Is there an option disable the watch of files and directories on the remote server?
If there is no such option would it be easy to add it?

The reason for such option is that sometimes the remote server could run out of free watching nodes and that would result in an errors.

Thank you!

**Comment by SchoofsKelvin** [comment]
The extension currently (perhaps wrongly) doesn't use any watchers. Whenever you focus an editor, click Refresh on the Explorer pane or similar, VS Code will poll the opened file/directory "manually" instead.
