### ISSUE TITLE
Disable warning

### ISSUE THREAD

**Issue by axelhuizinga** [SchoofsKelvin/vscode-sshfs#361]
How can I disable warnings like:
The home directory '/mnt/web217/e2/63/511726063/htdocs' in SSH FS <domain.net>' is not a directory, this might be a sign of bad permissions

**Comment by Cleanerrr** [comment]
I have sam problem. Any solution ???

**Comment by JohnnyMT** [comment]
Same here, but it only appears when I try to add the folder to the workspace... Terminal works fine btw.
I realized that terminal gets opened with the path I specified, but the error message shown when i try to add it to the workspace don't reflect that path?
Do you also have a path specified in your config?

**Comment by axelhuizinga** [comment]
Johnny are you talking about this one? (which I have on default now - adding workspace after key based login works well meanwhile - can't recall actually how I got rid of it)
Root Optional
Path on the remote server that should be opened by default when creating a terminal or using the `Add as Workspace folder` command/button. Defaults to `/`

**Comment by eherber** [comment]
same problem here

**Comment by SchoofsKelvin** [comment]
The Settings UI doesn't have an entry for this yet, but you can add a `-CHECK_HOME` flag (include the minus. see #270) to your config to disable the home directory check.
