### ISSUE TITLE
Remote Git repository

### ISSUE THREAD

**Issue by luisdatec** [SchoofsKelvin/vscode-sshfs#366]
I would like to know if is possible work with a Git repository that is located in the remote server.

I have removed the folder .git from the excluded options. Now, I can see the folder but the Visual Studio Code doesn't recognize the folder as a repository, and only suggest to create a new repository.

Is there a way to configure and open the remote git repository with the functions of Visual Studio code ?

![image](https://user-images.githubusercontent.com/18030230/208981276-19a5a223-a00c-4059-b987-1ab1e16b0927.png)

**Comment by ehudkaldor** [comment]
same here. anything?

**Comment by psolyca** [comment]
It's a long standing issue due to VSCode
Duplicate #31 
See https://github.com/microsoft/vscode/issues/109954

**Comment by luisdatec** [comment]
Thanks @psolyca . 

I have read, and now I am following issue: [#109954](https://github.com/microsoft/vscode/issues/109954).
