### ISSUE TITLE
Can path following be achieved?

### ISSUE THREAD

**Issue by TTT-TD** [SchoofsKelvin/vscode-sshfs#368]
I would like to be able to use the cd command in the terminal and at the same time make the remote file manager in the workspace go to the corresponding directory, please tell me how to do it.

Also, how can I use the sftp file manager in the workspace to access a directory using an absolute path?

**Comment by SchoofsKelvin** [comment]
By "going to the directory in the Explorer", you mean changing the root directory of the Explorer? VS Code doesn't like workspace (root) directories changing. This will e.g. restart all extensions meaning the SSH connection would also be disconnected.

That's separate from it being tricky to track `cd` calls in remote terminals on its own, but that's still doable.

As for absolute paths, the extension maps URIs such `ssh://<config-name>/absolute/path` automatically. I'm not entirely sure whether there's a convenient built-in way in VS Code to enter an absolute URI. For now, you can open a remote terminal, write the absolute path with a forward slash and ctrl-click it, or run `code /absolute/path` which is supported in most terminals.
