### ISSUE TITLE
Allow this extension the Resource Control??

### ISSUE THREAD

**Issue by developez** [SchoofsKelvin/vscode-sshfs#369]
Hello

I cannot use SSH Remote extensión from Microsoft because i have got problems with it (CPU to 100% and other issued), I am triying to use this but the problem is that SSH FS does detect the GIT repository and Source Control does not work.

Is possible??

![image](https://user-images.githubusercontent.com/1931408/221542300-7b1a00f7-af24-467b-8533-31ba69ecbdba.png)

**Comment by SchoofsKelvin** [comment]
Duplicate of #31
