### ISSUE TITLE
Build prerequisites

### ISSUE THREAD

**Issue by hamad12a** [SchoofsKelvin/vscode-sshfs#370]
I am relying on VSCODE as my IDE, I tried to build this repo using `yarn install` but the event ended with multiple errors that concern resolving modules conflicts. Each time I update one of them then building with `yarn build` , and even the tasks within the repo, throw errors. I spent a whole day after the building procedure I found myself in endless failures. I know it sound like it's straightforward but please consider to add the build instructions; my work relies on ***this great extension!***.

**Comment by SchoofsKelvin** [comment]
As a small note: the GitHub Workflow/Action still [works fine](https://github.com/SchoofsKelvin/vscode-sshfs/actions/runs/4515963195). I'll still have to update the runner/actions it use are (getting) deprecated, but this is separate from the actual build itself. I still suggest checking your Yarn version as a first step.
