### ISSUE TITLE
Tunelling arbitrary ip:port via the SSH Connection

### ISSUE THREAD

**Issue by erickweil** [SchoofsKelvin/vscode-sshfs#371]
If I open a terminal I can tunnel ports via ssh with the -L option
(see https://linuxize.com/post/how-to-setup-ssh-tunneling/)

For example, if I want to connect to example.server.com that from his internal networks sees a mysql database on ip 10.0.0.5, and I want to expose this service to my machine via the ssh connection I run:
ssh -L 3306:10.0.0.5:3306 user@example.server.com

And both the port is forwarded on my machine and the ssh connection opens to be used.

The Remote Explorer extension implements this by having a tab where you can put those ports mappings. But I don't want to consume 1Gb+ of RAM neither to have 200Mb+ of vscode trash just to easily forward a port.

There is any plans to implement port tunneling like this?

Note: I'm not talking about proxy the ssh connection itself, it's about reaching ports visible only inside the network of the server i'm connecting to.

**Comment by SchoofsKelvin** [comment]
Already in progress (#107 and e.g. #254). It's currently a beta feature on the `feature/forwarding` branch and not yet available in production.

**Comment by SchoofsKelvin** [comment]
Some more information:

- There's a [milestone](https://github.com/SchoofsKelvin/vscode-sshfs/milestone/1) regarding port forwarding
- There was already a beta release available with port forwarding, which I've just updated/improved. You can get the last build [from here](https://github.com/SchoofsKelvin/vscode-sshfs/actions/workflows/build-extension.yml?query=branch%3Afeature%2Fforwarding) and test the feature. There's a command, an option under the remote menu, and a button in the SSH connections pane
- While the UI isn't great yet, I'd say it's already very usable. There might still be some bugs. You can report those in #254 if it's UI-related or just create a new ticket
