### ISSUE TITLE
Add proxy support (documentation missing)

### ISSUE THREAD

**Issue by PaulPrice** [SchoofsKelvin/vscode-sshfs#38]
My ssh server is behind a firewall, so connections require a proxy. Using OpenSSH, this is possible with a `~/.ssh/config` setup like this:

```
Host server.com
  ProxyCommand ssh -q -W %h:%p user@proxy.com
  # Alternatives:
  #ProxyCommand ssh user@proxy.com exec nc %h %p 2> /dev/null
  #ProxyCommand ssh user@proxy.com 'exec 3<>/dev/tcp/server.com/22; cat <&3 & cat >&3;kill $!'
```

Such [capability appears to be available within ssh2](
https://github.com/mscdex/ssh2#connection-hopping), so please add support. I think it would be best if the proxy command were configurable (since `ssh-W` and `nc` aren't universal).

**Comment by PaulPrice** [comment]
On poking around, it looks like there is already support for this, via the `"hop"` configuration. Thank you so very much for anticipating my needs! Could we please reinterpret this issue as a request for documentation on this feature? I'm happy to contribute if you can give me some broad direction as to where you'd like it to live.

For posterity, here's a generic version of my configuration, demonstrating direct (to `direct.host.com`) and proxy connections (to `hidden.host.com` via `proxy.host.com`):
```
    "sshfs.configs": [
        // Example of connecting directly
        {
            "label": "direct connection",
            "root": "/home/user/directory",
            "host": "direct.host.com",
            "username": "user",
            "agent": "$SSH_AUTH_SOCK",
            "name": "direct"
        },
        // Example of connecting via proxy
        {
            "label": "Hidden server",
            "root": "/home/user/directory",
            "host": "hidden.host.com",
            "username": "user",
            "agent": "$SSH_AUTH_SOCK",
            "hop": "proxy",
            "name": "hidden"
        },
        // Example proxy configuration
        {
            "label": "Proxy connection",
            "host": "proxy.host.com",
            "username": "user",
            "agent": "$SSH_AUTH_SOCK",
            "name": "proxy"
        }
    ],
```

**Comment by SchoofsKelvin** [comment]
While the config scheme does include the proxy (and hop) config settings, I do still have to write the documentation for this, along with a very few other features.

Added a new issue #43 with a task list for documentation.

**Comment by pranavz189** [comment]
Documentation for this feature would be great. Thanks !
