### ISSUE TITLE
Make JSON schema validation available locally

### ISSUE THREAD

**Issue by avylove** [SchoofsKelvin/vscode-sshfs#40]
When running without an internet connection, I get the following error. There should be no need to make external web calls.

`Problems loading reference 'https://raw.githubusercontent.com/SchoofsKelvin/vscode-sshfs/27dec3277d9a50869c3d2a11db21da6e07a3223a/settingsschema.json': Unable to load schema from 'https://raw.githubusercontent.com/SchoofsKelvin/vscode-sshfs/27dec3277d9a50869c3d2a11db21da6e07a3223a/settingsschema.json': Unable to connect to https://raw.githubusercontent.com/SchoofsKelvin/vscode-sshfs/27dec3277d9a50869c3d2a11db21da6e07a3223a/settingsschema.json. Error: unable to verify the first certificate`

**Comment by SchoofsKelvin** [comment]
The schema validation for User Settings is now included locally (74b0727b)

Note: Using the extension's "config editor" still requires to fetch the remote schemas (for now)
