### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by fnkcgxgkgcfu** [SchoofsKelvin/vscode-sshfs#402]
On the Visual Studio Code config.json file the SSH login info is explicitly visible and with no encryption, I want to know why such important info is not hideen?

**EXAMPLE**

"sshfs.configs": [
        {
            "name": "root",
            "host": "192.168.1.1",
            "port": 22,
            "password": "password",
            "username": "root"
        }

**Comment by colin-r-schultz** [comment]
The configuration page explicitly says that the password is stored in plain text, and it is therefore not recommended to use that option.

> Password
Password for password-based user authentication. Supports env variables. This gets saved in plaintext! Using prompts or private keys is recommended!

**Comment by fnkcgxgkgcfu** [comment]
> The configuration page explicitly says that the password is stored in plain text, and it is therefore not recommended to use that option.
> 
> > Password
> > Password for password-based user authentication. Supports env variables. This gets saved in plaintext! Using prompts or private keys is recommended!
