### ISSUE TITLE
Can't connect to server as user

### ISSUE THREAD

**Issue by Chillifish** [SchoofsKelvin/vscode-sshfs#41]
Perhaps I'm not doing it correctly, but I seem to be unable to connect to my server as a user, only as root. If I connect as root, it's fine, if I connect as a user, I just get the error "Permission denied".

**Comment by Chillifish** [comment]
I suspect it's a security certificate issue.

**Comment by SchoofsKelvin** [comment]
This sounds as if you're trying to use a remote directory as `root` folder that your user doesn't have (read) access to. When you SSH into the server as the user, can you go to the specified `root` folder and see what's in it?

**Comment by Chillifish** [comment]
Sorry, I'm not quite sure I follow. I'm just trying to log in as a user, not specifying any directory. If I log in as root, no problem. If I log in as user, "Permission denied" comes up. I'm thinking it's a security certificate issue as if I try and connect with SFTP Net Drive, I get a message box about the security certificate and then it refuses to connect. On my Mac, I can connect as a user fine using cyberduck, but have the same issue with this extension and VS Code.

**Comment by SchoofsKelvin** [comment]
What root folder are you using? In your config you have a field `name`, but there's also an optional field `root`, which defaults to `/`. If you don't specify it, the remote workspace will be your whole remote filesystem. Usually, the root user can freely access it while no other users can.

Try adding `"root": "~"` *(or use the direct path)* to use the user's home directory as root. See if that also results in a permission error.

**Comment by Chillifish** [comment]
Ah, that's done it thanks. I misunderstood the documentation and thought that the root defaulted to the root folder for the user, rather than the root folder of the connection
