### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by SchoofsKelvin** [SchoofsKelvin/vscode-sshfs#43]
**Create small overview page (either with sections or links)**
- [X] Introduction
- [X] Basic usage / config
- [ ] All configuration options
	- [ ] Proxy support
	- [ ] Hopping support
	- [ ] Authentication
	- [ ] PuTTY/agent integration
- [ ] Revamped TO DO list
- [ ] Updated schema validation

**Comment by kleinicke** [comment]
Add a shortened version of the configure, so everyone can just try out this plug in, even without knowledge what fields to use and what not to use. Just like for the putty case. This short version just works when the username and hostname is modified and the Passwort is entered when connecting.
{
            // Unique id, which results in ssh://serverlogs/
            "name": "Goodname",
            // Remote folder to use as root (default is /)
            //"root": "/homefolder",
            // Host to connect to (domain / IPv4 / IPv6)
            "host": "server.com",
            // Port to connect to (default is 22)
            "port": 22,
            // Username to login with
            "username": "me",

            "password": true,
        },

**Comment by SchoofsKelvin** [comment]
Closing since the Settings UI already provides most documentation for configuration. The README just kickstarts you into using the Settings UI and Command Palette.
