### ISSUE TITLE
can we direct copy from remote to my desktop?

### ISSUE THREAD

**Issue by plustick** [SchoofsKelvin/vscode-sshfs#44]
I wish to copy transport from temote to my desktop any editing file for my local repository ?

i had drag the file  to desk top and explorer pane,but could not copy .it mouse pointer icon was (deny copy X red color icon)

**Comment by SchoofsKelvin** [comment]
My extension provides vscode with a list of all files in a directory when asked, along with the possibility to write/read files. This dragging issue seems to be a (possibly intended?) bug in vscode itself. I can't enable (or disable) drag-drop support on my end as far as I can tell.
