### ISSUE TITLE
Commond not found,never working

### ISSUE THREAD

**Issue by V0idk** [SchoofsKelvin/vscode-sshfs#47]
![peek 2018-09-21 01-05](https://user-images.githubusercontent.com/17514799/45834692-6b416200-bd3a-11e8-87e0-970424caa18d.gif)

**Comment by SchoofsKelvin** [comment]
Does this also happen after reloading/restarting vscode?

This issue (#37) appears now and then for some people, but I can't reproduce it, nor find a cause. It's usually fixed after restarting vscode, and might not appear again for a long time.

**Comment by Jooyoung01** [comment]
When I **reboot the OS** (Windows10), this problem was resolved...

**Comment by SchoofsKelvin** [comment]
Seems like it is indeed something I can't resolve then, if rebooting your OS somehow fixed it
