### ISSUE TITLE
Problematic SSH disconnections

### ISSUE THREAD

**Issue by opportus** [SchoofsKelvin/vscode-sshfs#49]
Hello there,

I'm currently working on a remote server that temporally ban IPs that connect too often on SSH port in a relatively short amount of time...

Something keeps getting my VSCode environment disconnected from this server every 10 minutes or so. Since I naturally have to reconnect, my IP gets temporally banned...

Are these disconnects caused by the vscode-sshfs extension? If so, are they intended and is there a way to modify that behavior?

Thanks by advance for your help.

**Comment by SchoofsKelvin** [comment]
The extension shouldn't disconnect the connection unless you actually try to disconnect, either using the command, a rightclick menu, or by closing the workspace folder. There might be a timeout configured on the server for SSH sessions.

Does it only disconnect when you've been idle (not reading/writing folders/files for a while), or even right after you've modified the file system from vscode? Otherwise I could add a repeating task to fetch the root directory, as to not get timed out for being idle for too long.

**Comment by opportus** [comment]
Hi @SchoofsKelvin,

That's not from the server for sure because I have worked for a while on it with different SSH clients on different OS and never got that kind of disconnection.

On my Windows 10 (VSCode `v1.27.2` / SSHFS `v1.9.2`), I can reproduce the issue by following these steps:

1. Excecute VSCode
2. Right click on "Server" in SSH File Systems in the file explorer panel and select "Connect Workspace folder"
3. Work on some files from the server (the issue also happens even if we ignore this step)
4. Keep the VSCode window focus (don't do anything, don't change window)
5. Few minutes later, try to open another file from the server

Then I get the VSC notification:

> SSH FS Server disconnected
> Source SSH FS (Extension)

Also note that the "led" on the "Server" file system is still green when the disconnect happens.

Here is my SSHFS config file `server.sshfs.jsonc`:
```json
{
    "label": "Server",
    "root": "/srv/http",
    "host": "example.com",
    "port": 22,
    "username": "**********",
    "password": false,
    "privateKeyPath": "D:\\\\.ssh\\\\server_rsa",
    "passphrase": "**********"
}
```

**Comment by SchoofsKelvin** [comment]
I'll see adding timeouts to one of my servers and reproducing this issue. It might be those other clients already use something to prevent the connection from timing out.

**Comment by DarthSpock** [comment]
> Otherwise I could add a repeating task to fetch the root directory, as to not get timed out for being idle for too long.

Please do this. I did experience this and it's a pain to have to enter my password all over again after being idle some amount of time, which I can't save for security reasons. Just basically need keep-alives to be sent every 5 minutes when idle so the connection doesn't time out.

**Comment by RaunoT** [comment]
Same issues for me. 
Hope that keepalives will be implemented in the near future.

**Comment by schrej** [comment]
You should actually be able to add the following to the configuration:
```json
"keepaliveInterval": 300
```
It's an option of SSH2 and the configuration gets passed through to it. It should then send a keepalive every 300 seconds (change to whatever you need of course).

**Comment by DarthSpock** [comment]
I knew there had to be a simple solution and you provided it! This can be done now or does it need to be put into the extension first? It would help if it was a default so that we don't need to touch the config.

**Comment by schrej** [comment]
This can be done now. Just add it to your connection config. It would be nice to be able to configure it globally though.

**Comment by SchoofsKelvin** [comment]
Ah, that's what that option is for. Somehow I thought it was meant as in "how long to keep the session open", with the default `0` meaning "forever"

I might actually add a default myself of 30 seconds, which should cover most (if not all) cases of timeouts.
