### ISSUE TITLE
Run a custom commands after connected

### ISSUE THREAD

**Issue by FabienZa** [SchoofsKelvin/vscode-sshfs#50]
Thanks a lot for your extensions.

I have a request, may be it's already implemented , but I don't find it. Is it possible to run a custom command after connexion ? Like that we will can run for example `sudo su -` ?

It's possible on an other extension, "SSHExtension", but there are no FS provided with this one.

Have a nice week,
Fabien

**Comment by SchoofsKelvin** [comment]
Solved in issue #28
