### ISSUE TITLE
Error while reading the keyfile at: ~/.ssh/id_rsa

### ISSUE THREAD

**Issue by samwiseduzer** [SchoofsKelvin/vscode-sshfs#52]
OS: OSX 10.13

I've verified that this path is readable, and contains a valid OpenSSH key that works, but when I try to connect through the sshfs extension, I get the error:

Error while reading the keyfile at: ~/.ssh/id_rsa

I could totally just be noobishly missing something, or perhaps I don't understand the scope of this project, but I'm tearing my hair out trying to figure this out.

**Comment by samwiseduzer** [comment]
I learned that I had to use the absolute path and it then worked

**Comment by Trimakas** [comment]
I think I'm in your same boat at the moment.. getting the same error and trying the absolute path but that doesn't want to work either.. what exactly did you put in your config file??
