### ISSUE TITLE
Cannot save remote file with ":w" in Vim emulation, but File -> Save works

### ISSUE THREAD

**Issue by ludwigschmidt** [SchoofsKelvin/vscode-sshfs#53]
I just installed vscode-sshfs and successfully connected to a remote file system via SSH with a key file (Mac OS X is running on my local machine, Ubuntu on the remote one). However, when I try to save a file with ":w" (the standard command in Vim), the status bar at the bottom of VS Code displays error messages of the following form:

> ENOENT: no such file or directory, access '/home/ubuntu/path/to/remote/file.py'

When I save the same file via File -> Save in the menu (or the corresponding shortcut), the content is written correctly to the remote file system. I have also verified that I can successfully mount and edit remote files with `sshfs` outside VS Code.

Is this an error in my setup or a bug in VS Code / the SSHFS extension?

Thank you for making this great extension!

Some more info:
- VS Code version 1.27.1
- SSH FS extension version 1.9.3
- `sshfs` version:
```
$ sshfs --version
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE library version: FUSE 2.7.3 / OSXFUSE 2.8.2
```

**Comment by SchoofsKelvin** [comment]
Are you using vim on your local client, or on the remote server?
If it's the latter, then the extension shouldn't have any effect on it.
If it's used on the client, it's a bit strange, as the extension only provides the remote filesystem in/for vscode. You shouldn't be able to use other programs with it.

If you've mounted the remote server on your own client using sshfs, then you should check the path. That error message makes me think you're trying to edit `/home/ubuntu/...` *on your Mac*. Shouldn't it be something like `/mnt/remote/home/ubuntu/...`?

**Comment by ludwigschmidt** [comment]
Sorry for the confusion. I did not try ":w" to save in an actual vim session, I am using the Vim extension in VS Code. I would have expected ":w" to work the same way as File -> Save, but this does not seem to be the case.

**Comment by SchoofsKelvin** [comment]
Ah, this must be similar to some other issues, e.g. #43 

Basically, the extension should support using the new FileSystemProvider API added in 1.23.0 of vscode. It most likely is trying to read/modify your local disk.

Unless the vscode team made progress on it in the last few days, there isn't an easy way for extensions right now to read/write "remote files", thus I don't expect the extension to support this soon.

**Comment by ludwigschmidt** [comment]
OK, thank you for your help!

It looks like the VIM extension already has an issue for this problem:

https://github.com/VSCodeVim/Vim/issues/2986
