### ISSUE TITLE
Feature request: support connection hopping

### ISSUE THREAD

**Issue by mjbnz** [SchoofsKelvin/vscode-sshfs#54]
Sometimes I need to hop through bastion hosts to access files for editing.

Currently, I'm using an sshfs mount on the bastion host, but this is suboptimal. liximomo/vscode-sftp has hop support, but doesn't support agent authentication. Implementation is [here.](https://github.com/liximomo/vscode-sftp/blob/master/src/core/remote-client/sshClient.ts).

**Comment by SchoofsKelvin** [comment]
Although it isn't properly documented, connection is hopping (with, unless I did something wrong, agent support) is implemented: #4 

If that's not exactly what you need, feel free to reopen the issue with more information.

**Comment by mjbnz** [comment]
So, if I understand that correctly, that still requires an external terminal running to run the socks proxy for the extension to connect to.. if ssh2 supports creating socks proxies, then it might be nice to be able to do something like:

```
{
    "label": "remote-internal",
    "host": "internal-hostname",
    .......
    "uses-proxy": "remote-bastion",
}
{
    "label": "remote-bastion",
    "host": "hostname",
    .....
    "create-proxy": {
        "type": "socks4",
        "port": 9159,
    }
}
```

Otherwise, hopping like vscode-sftp does would be preferable, as then I'm not relying on an extra application running on my PC. (In this situation, I'm not running putty to connect)

**Comment by mjbnz** [comment]
And I just found #7 which appears to be what I want... just not documented. ;)
