### ISSUE TITLE
agent authentication fails on mac OSX

### ISSUE THREAD

**Issue by chbndrhnns** [SchoofsKelvin/vscode-sshfs#55]
My configuration is like this:

```json
{
    "label": "a",
    "root": "/home/docker/a",
    "host": "server",
    "port": 22,
    "username": "b",
    "privateKeyPath": "/Users/b/.ssh/keys/id_rsa",
    "agent": "$SSH_AUTH_SOCK"
}
```

I end up with the error `Error while connecting to SSH FS s:
Encrypted private key detected, but no passphrase given` although my ssh key is cached in the ssh-agent and I can connect on the console without entering a passphrase. If I add `passphrase: true` to the config, I am prompted every time I connect and the connection succeeds.

**Comment by SchoofsKelvin** [comment]
Try removing the `privateKeyPath` field. The ssh2 library tries the private key before the agent when a private key is given. There is currently no (easy) way for me to solve this.

**Comment by SchoofsKelvin** [comment]
I'll make a note to explain this properly in the new documentation (#43)
