### ISSUE TITLE
Unable to connect with Pageant: timed out while waiting for handshake

### ISSUE THREAD

**Issue by anthosz** [SchoofsKelvin/vscode-sshfs#57]
Hello,

I cannot connect to servers with sshfs for vsc on W7.

I have always this error (pageant & putty works):
"Error while connecting to SSH FS server: Timed out while waiting for handshake"

Configuration of sshfs:

> "sshfs.configs": [
        {
            "name": "server1",
            "root": "/tmp",
            "host": "server1",
            "port": 22,
            "username": "test",
            "agent": "pageant"
        },
        {
            "name": "test",
            "putty": "server2",
            "root": "/tmp"
        }
    ]

Do you have any idea to fix this?

Best regards,

**Comment by SchoofsKelvin** [comment]
Can you connect using the same host/port/... in PuTTY or any other SSH client?

**Comment by SchoofsKelvin** [comment]
Does logging in using PuTTY (or any other client) take a long time?

There isn't a clientside timeout mechanism in the ssh2 library that I use, so it's highly unlikely. The fact that you can connect using PuTTY means the server/port should be correct.

**Comment by anthosz** [comment]
The connection via Putty is immediate but I do not know if it can be linked, there is a proxy configured on Windows.. This is used by sshfs? (So I try sshfs with 2 servers (external & internal), I have the same issue with both)

**Comment by SchoofsKelvin** [comment]
I'm not entirely sure what PuTTY does different connection-wise, unless the proxies used are different. Where on Windows did you configure this proxy?

**Comment by SchoofsKelvin** [comment]
Ah, that might be why. I personally haven't added anything to take those in account.

Unless it's a special or complicated kind of proxy, you could change the config to make use of it (see #4 or #7 for the current "documentation" about it)

**Comment by anthosz** [comment]
Unfortunately, this is not possible (restricted rights) :(

Like workaround, can be good to have an option to ignore (or force) all proxy in the module? (If possible)

**Comment by SchoofsKelvin** [comment]
The extension supports SSH hopping (#7), along with HTTP (#64) and SOCK4/SOCK5 (#4) proxies. It seems like Windows also supports HTTPS/FTP, which I could add support for if needed. I'm not really planning on fetching Windows proxy settings and keeping these in mind.
