### ISSUE TITLE
Multiple folders same server?

### ISSUE THREAD

**Issue by lostarchitect** [SchoofsKelvin/vscode-sshfs#59]
Hello!

I was just wondering (and hoping) if it's possible to have one connection to the SSH server but for my ease have multiple folders presented, such as:
/home/james
/var/www/
/var/logs

To essentially be shortcuts to places I access the most.

I'm sure this could be done by making a workspace with multiple server instances from your extension, but I'd ideally like to re-use the single server connection than having one connection for each folder, especially as I don't want to be prompted for a password for each folder.

Is this doable right now, if so can you tell me how please, and if not could you please make that a possibility?

Thanks, James.

**Comment by lostarchitect** [comment]
Hey, so I just found the solution to this.

Setup your SSH FS with the root as '/' and then make a workspace file have something like:
{
	"folders": [
		{
			"uri": "ssh://server/home/james",
			"name": "James Home"
		},
		{
			"uri": "ssh://server/home/james/public_html",
			"name": "James WWW"
		},
		{
			"uri": "ssh://server/var/logs",
			"name": "Server Logs"
		}
	]
}

Thanks for the great extension!

**Comment by SchoofsKelvin** [comment]
Note to self: Add to documentation as a useful "multiple folders, single connection" kind of thing (#43)

**Comment by leifnel** [comment]
Could you be a little more specific on where the folder json above is to be? In the settings.js?

**Comment by SchoofsKelvin** [comment]
The `folders` one is visible when you open the Workspace Settings in JSON mode

**Comment by gyohza** [comment]
Life-saver! Can we have this thread renamed and labeled so it is a bit clearer?

This was *exactly* what I was looking for, but took me a while until I found it - a few seconds short of filing a new issue, actually.

I think it's important to include terms such as `shortcut`, `initial folder path` and related keywords. It was kind of a pain having to navigate all the way through to `/var/www/html/my_proj`.

It does need to be included in the documentation, though.

**Comment by SchoofsKelvin** [comment]
> I think it's important to include terms such as `shortcut`, `initial folder path` and related keywords
*@gyohza*

With terms, do you mean config options? There is a config option `root` to specify which remote folder will be used as root. E.g. if your root is configured as `/var/www`, then `ssh://myconfigname/html/my_proj` would point to `/var/www/html/my_proj` *(and your workspace folder would start at `/var/www`)*

**Comment by gyohza** [comment]
@SchoofsKelvin

Nope, I meant as labels or words to use in the thread title. It took me quite some time to find it, I just don't think it was clear that I would find what I was looking for judging by this thread's title.
