### ISSUE TITLE
Unable to load schema when creating sshfs config

### ISSUE THREAD

**Issue by DarthSpock** [SchoofsKelvin/vscode-sshfs#60]
When attempting to create a SSHFS configuration, the resulting jsonc file fails to save. Due to this, it does not show up and therefore can't connect to the remote mount.

**Comment by nunure** [comment]
What kind of error message do you have when you attempt to save the file ?
The jsonc file is only writting the conf in your user settings.

You can try hadding your configuration into your user settings like the following:

``` json
"sshfs.configs": [
    {
        "root": "/tmp",
        "host": "localhost",
        "port": 22,
        "username": "root",
        "password": "CorrectHorseBatteryStaple"
    }
],
````

**Comment by DarthSpock** [comment]
This may actually be a bug with code because it did the same error for trying to save jsonc files for other extensions.  If so, it would be a regression.

**Comment by DarthSpock** [comment]
I may be able to confirm as bug. I uninstalled VS Code entirely, including extensions and settings and then reinstalled Insiders and extensions. After this, I was able to successfully mount my Linux box. So something in Insiders fixed the issue.
