### ISSUE TITLE
Recursive copy folders between local and remote

### ISSUE THREAD

**Issue by llegolas** [SchoofsKelvin/vscode-sshfs#63]
Is this feature possible ? 
Is there a way to refresh remote folder content ?

**Comment by SchoofsKelvin** [comment]
Pressing the Refresh button (at the top of the Explorer pane) should refresh all folders.

Currently (and for the foreseeable future) the extension doesn't support "transferring" folders or files. It's merely for vscode to read/write remote files/folders. For this, you're better off using a (S)FTP client, SCP, ...
