### ISSUE TITLE
Enable offline file persistence for files created in remote directories

### ISSUE THREAD

**Issue by DarthSpock** [SchoofsKelvin/vscode-sshfs#67]
While I still have a file open when I disconnect from my remote workspace due to disconnecting from the corporate network (but connecting back to the Internet), I'd like my file to still be read by VS Code to continue editing. When I re-connect to the corporate network and start the re-connection to my remote mount, the changes would then be synced back to the source file located on the mount to reflect the changes before being able to edit once more. If there is another extension that can achieve this result, I would accept that as a workaround (but not the final solution).

VS Code version: 1.29 (Insiders)

**Comment by SchoofsKelvin** [comment]
This is not exactly what this extension is about. It's supposed to be as "live" and up-to-date as possible.

If you really want it being cached on your computer, you might want to look into a "sync program" or any program with (continuous) synchronization, which e.g. WinSCP has as a built-in feature.

I might add this as a feature in the future, but this would require me to check for and properly handle connection loss, local file caching, ... but this isn't planned right now, and would take quite a bit of time too.

I'll keep this issue open for a bit, while I think whether I should implement it and if I would, in what way.

**Comment by DarthSpock** [comment]
Revaluating this, it probably would be better to make use of some other extension such as VS Live Share or an API within Code and use that to perform syncs from local workspace to ssh workspace.

**Comment by SchoofsKelvin** [comment]
Closing this issue now. This doesn't seem like a feature I see being added to this extension, as it goes against the whole "live remote" side of this.
