### ISSUE TITLE
How do I use the insider branch version?

### ISSUE THREAD

**Issue by digitalbaboon** [SchoofsKelvin/vscode-sshfs#68]
Hi! Could anyone please lay out a simple tutorial on how do I use the Insider branch version of the plugin (I'm rather desperate for the file search ..). All help is appreciated :)

**Comment by SchoofsKelvin** [comment]
If it is for working on this extension, you could clone the insider branch and run the extension in vscode, as if you're working on a regular vscode extension, should you have experience with that. Mind that you probably need to use `--enable-proposed-api Kelvin.vscode-sshfs` when launching vscode (with no other vscode window being open) for the proposed API things to work. You could also run `vsce package` to create a .vsix file that you can directly install in vscode insider, which doesn't require you to "run" the extension in debug mode.

The insider branch is several major versions behind, so it isn't really *advised* to try running it. I'll start updating it later today, which might take a while. They deprecated the search API from a few versions back that the insider branch still uses, so I'll have to implement the new way of searching things.

**Comment by digitalbaboon** [comment]
Ah, gotcha! This answers my question so I'll close this issue. Thank you!
