### ISSUE TITLE
could sshfs distinguish case?

### ISSUE THREAD

**Issue by KeWang323** [SchoofsKelvin/vscode-sshfs#69]
Hi!
I have such structure on my remote ubuntu server, where "workspace" is a folder and "WORKSPACE" is a file. Currently it ignores "workspace" for me, so that no "workspace" on the left EXPLORER. Is that possible sshfs supports that like linux? Thank you! I really enjoy the plug-in:)

folder
 |──workspace
 |──WORKSPACE

**Comment by SchoofsKelvin** [comment]
*Duplicate of #32*

This is currently a bug *(or a lack of feature)* in vscode: Microsoft/vscode#48258 and can't be fixed for now
