### ISSUE TITLE
"editor.formatOnSave" and "Format Document" do not work

### ISSUE THREAD

**Issue by kwinz** [SchoofsKelvin/vscode-sshfs#72]
Trying to format the current document fails.
Neither the command `>Format Document`, nor the setting` "editor.formatOnSave": true` work.
If I edit something on the local harddisk everything works as expected.
I have tried https://github.com/xaverh/vscode-clang-format-provider which works on local documents.

**Comment by cloudhan** [comment]
Same issue here, format region doesn't neither

**Comment by SchoofsKelvin** [comment]
This is similar to issue #42, as in that this isn't something I can fix. The extension only works for local files, as it uses an executable internally. The extension itself would need to add support for workspaces using the FileSystemProvider API.
