### ISSUE TITLE
can't use F12(go to definition) function in ssh fs mode

### ISSUE THREAD

**Issue by GoldenJuly** [SchoofsKelvin/vscode-sshfs#74]
after connecting a server folder use ssh fs, i can't use F12(go to definition) function，problem as follows:
it reminders me "no definition found for xxx", but xxx is easy to find in the same file

**Comment by SchoofsKelvin** [comment]
This seems to be part of #16 and similar issues. This should be reported on the vscode (TypeScript Language Extension?) issue tracker instead, although they should already know by now.

**Comment by chrysochos** [comment]
Go to definition is not working for files over SSH FS. I tried from Windows 10 and Ubuntu 18.04 vscode and the results were the same.
