### ISSUE TITLE
Log or output

### ISSUE THREAD

**Issue by PierreMarchand20** [SchoofsKelvin/vscode-sshfs#79]
I am trying to use this extension to log to a remote server via another server. I saw how to do hopping, but I guess I have an error in my config somewhere. But I could not find any output or log to try to debug. 

Would it be possible to use the Output window in VSCode to show what is happening ? It would help the user to understand what is wrong when it is not working.

**Comment by PierreMarchand20** [comment]
Or when it asks for a password, it would be nice to see which host ask it by printing the ```name``` or the ```host```

**Comment by inetknght** [comment]
I've tried using this on both Linux and Windows (without hopping).

On Linux this seems pretty straightforward. I don't use an agent there and the configuration works on first try for keys without a passphrase (and haven't tried keys with a passphrase... maybe later).

On Windows, I'm using Pageant. I'm not sure I'm doing it right. I don't see any logs anywhere to even try to debug my configuration. All I see is that "all configured authentication methods failed". I don't see a request to enter my passphrase nor a password. I definitely do _not_ want to write passwords or passphrases in my configuration; I want it to prompt me for either and/or both.

It would be handy to have the ability to configure log verbosity and write logs to the Output pane under a section specifically for SSHFS, perhaps even configurable to subsections by specific servers.

**Comment by SchoofsKelvin** [comment]
When asking for a username/password/passphrase, the prompt will now display the username (if known) and host (2d0a092). I've also added some initial logging, visible under the Output pane once the extension has been activated (151d72c)

Both changes are live under version 1.12.0 of the extension.

I'll be expanding the logging later on, but some things, e.g. authenticating, are mostly handled by the ssh2 library I use. While it has some logging/debug capacities, it's limited, but I'll look into that.

**Comment by SchoofsKelvin** [comment]
Logging has been improved over time.
Under `Output > ssh-fs` quite a bit of info is logged, including stacktraces for caught errors.
