### ISSUE TITLE
rsa key file instead of string

### ISSUE THREAD

**Issue by knkumar** [SchoofsKelvin/vscode-sshfs#8]
adding the private key as string is impossible for me, can you change it to take in the file and authenticate automatically?

**Comment by SchoofsKelvin** [comment]
I can add a field `privateKeyFile` to read the private key from a file. If you meant to read the key files from `~/.ssh/config`, that'll take a bit longer to implement.

**Comment by knkumar** [comment]
I think adding a location should be good, I can point it to any file in ~/.ssh/ in case I have multiple keys. I hate typing my passwords to all my remote servers. I think this addition would make it 5 stars for me.

**Comment by SchoofsKelvin** [comment]
Support for environment variables added in ee40dcb (published in 1.6.0)
