### ISSUE TITLE
pylint post a error in line 1

### ISSUE THREAD

**Issue by zpd2009** [SchoofsKelvin/vscode-sshfs#80]
[pylint] F0001:No module named /workspace/pyworkspace/test/test.py [F0001]

File name is test.py and path is /workspace/pyworkspace/test
----------------------------------------
1 #
2 #
3 print("Hello world!")
----------------------------------------

In line 1 doesnot has any thing...

thank you~

**Comment by SchoofsKelvin** [comment]
While this issue is pretty vague, it's most likely related to #42.
