### ISSUE TITLE
Move sshfs settings to separate file

### ISSUE THREAD

**Issue by PSVortex** [SchoofsKelvin/vscode-sshfs#81]
Hi,
please move sshfs settings to separate file, it can be global or per-folder/workspace. Then anyone can add it to .gitignore and avoid situation when unwanted data will be synced along with VSCode Settings file.

**Comment by jcklpe** [comment]
Agreed. I find this really useful but I also sync my vscode settings to a public gist and I'm not super keen on having my username and folder structure publicly available. Yeah, I could just not sync my stuff via gist, but I share my dotfiles through a git repo, and if I have to choose between giving up on this extension or giving up on the ease of public syncing and having a nice easy to access source control repo for my configs then... well I'm going to give up the extension. The other stuff is just much more important for me.

**Comment by SchoofsKelvin** [comment]
The extension uses the built-in settings file(s) of vscode. You can put configurations in the User Settings, Workspace Settings and even folder settings. Is your issue about synchronizing the .vscode folder in a project's workspace, or are you actually synchronizing the main User Settings file?

**Comment by jcklpe** [comment]
I'm syncing the main user setting file.

**Comment by SchoofsKelvin** [comment]
I'm reworking how configs are loaded and handled. One of the new features that will introduce is a config `sshfs.configpaths` with paths to JSON files to load configs from. Also, the extension will look for sshfs.json and sshjfs.jsonc in the current workspace folders. These would have this format:
```jsonc
[
	{
		"name": "my-server"
		// ...
	},
	// ...
]
```
I'm still working out some issues, including a replacement for the New/Edit/Delete Configuration commands, as those would be incompatible with the new system. If it takes too long, I might release the new system with temporarily no replacement for those.

**Comment by PSVortex** [comment]
@SchoofsKelvin Thanks for extra jsonc!

**Comment by SchoofsKelvin** [comment]
This is live in 1.14.0, along with a new command `SSH: Open settings and edit configurations` which gives you a... "decent" UI for viewing/editing the main fields of all configs.

Basically, add something like this to your global/workspace settings:
```jsonc
  "sshfs.configpaths": [
    "C:\\Some\\Path\\sshfs.test.jsonc"
  ],
```
That'll make the extension look for configurations in the given path. It uses the JSONC parser (even for .json files), so adding comments in the config files are, just like vscode's settings.json, allowed. The config files should contain an array with configs, like this:
```jsonc
[
    { // just testing stuff
        "label": "Config file test",
        "name": "config-file-test",
        "putty": "testsession",
        "root": "/var/www",
    },
    {
        "name": "test",
        "putty": "testsession"
    },
    {
	// This one will be merged with the "next" ones instead
	// Configs get loaded in this order:
	// Workspace settings,  all files from "sshfs.configpaths" in Workspace settings in order,
	// Global settings,  all files from "sshfs.configpaths" in Global settings in order
	// So if you have configs with the same name in Workspace Settings and Global Settings,
	// it'll use the one from the Workspace settings, not the one from Globals.
	// If the Workspace one has `merge` set to true, it'll instead use the ones from Globals
	// but overwrite all the given values from the Workspace one
        "name": "merged",
        "username": "user2", // No matter what the Globals one says, use this username
                                          // (assuming this file is loaded from a Workspace config file)
        "merge": true,
    },
]
```

I'll probably change the order to `Workspace files > Workspace settings > Global files > Global settings`, as that makes more sense now than when I implemented it. I'll probably also add support for `${workspaceRoot}` and such later on.

The automatic use of files from `${workspace}/sshfs.json` and `${workspace}/sshfs.jsonc` is disabled for now. You can "reimplement" this by having `"sshfs.configpaths": ["fullpath/sshfs.jsonc"]` in the workspace's settings. Not very clean and useful, so definitely gonna improve that soon.

**Comment by jcklpe** [comment]
Awesome! Thanks!
