### ISSUE TITLE
How do I use this with Vagrant?

### ISSUE THREAD

**Issue by amfsyn** [SchoofsKelvin/vscode-sshfs#82]
I can't connect to my Vagrant box.
When I ssh in myself, I use `vagrant ssh` which calls `ssh -F` and supplies the output from `vagrant ssh-config` as the config file. How do I pass in all the options from ssh-config?

vagrant ssh-config output:

Host my-vagrant
  HostName 172.16.70.180
  User vagrant-project
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/me/Dev/vagrant-project/.vagrant/machines/irflow-dev/vmware_fusion/private_key
  IdentitiesOnly yes
  LogLevel FATAL

Is there a way I can pass all of the options in this configuration file?

**Comment by SchoofsKelvin** [comment]
I haven't heard of Vagrant before, but most of these config values can be used in a sshfs configuration:
```jsonc
// settings.json (User Settings, Workspace Settings, ...)
{
  "sshfs.configs": [
    {
      "root": "/", // Could also be "~" if you don't need access to /etc or so
      "label": "Vagrant",
      "name": "vagrant",
      "host": "172.16.70.180",
      "port": 22,
      "privateKeyPath", "/Users/me/Dev/vagrant-project/.vagrant/machines/irflow-dev/vmware_fusion/private_key",
      "passphrase": true // If the private key requires a key, this will make the extension prompt you for one
    }
}
```

That should work, based on the given configuration.
