### ISSUE TITLE
How to use the Windows 10 integrated ssh(-agent)

### ISSUE THREAD

**Issue by glatzert** [SchoofsKelvin/vscode-sshfs#83]
Windows 10 now comes with integrated ssh client and ssh-agent, which I'd like to use here, but I cannot figure out what I need to set, to make that work.
Do you have any advice on that?

**Comment by SchoofsKelvin** [comment]
I've worked a bit on this before, and was waiting on this PR in a dependency: mscdex/ssh2#748. I updated the dependency (a1fb2da) to a version with this fix, and released this under version 1.12.0 of this extension.

To make use of this, use `"agent": "//./pipe/openssh-ssh-agent"` in your sshfs config.

**Comment by dsolodow** [comment]
Excellent news. :) Should the updated version be in the Marketplace in the next day or two?

**Comment by SchoofsKelvin** [comment]
I just published 1.12.0 to the marketplace. It should be live now, give or take a few minutes for the marketplace to catch up.

**Comment by glatzert** [comment]
Tried it out - works nicely!
Thanks for your work!

**Comment by DarthSpock** [comment]
where do you place the config?
