### ISSUE TITLE
StrictHostKeyChecking

### ISSUE THREAD

**Issue by ndegara** [SchoofsKelvin/vscode-sshfs#89]
Is there any way to add additional options to the way ssh is called such as
StrictHostKeyChecking=no?

Thanks!

**Comment by SchoofsKelvin** [comment]
Most config options are just passed on to the [ssh2 library](https://www.npmjs.com/package/ssh2) I use. For StrictHostKeyChecking, it seems like it allows any key by default already. Did you run into a problem related to that?
