### ISSUE TITLE
fails to reconenct

### ISSUE THREAD

**Issue by dvdobrovolskiy** [SchoofsKelvin/vscode-sshfs#9]
If files not access some time it hangs on reconnect showing loading animation. Sometime "Reconnect Workspace folder" helps but mostly not. Only restart of IDE

**Comment by SchoofsKelvin** [comment]
I haven't really looked into the connection timing out, or closing after a successful connect in general. I'll add event listeners for this, and either automatically reconnect, display a warning, or choose one of these two depending on a config option.

**Comment by dvdobrovolskiy** [comment]
thanks!

**Comment by SchoofsKelvin** [comment]
This issue should be fixed in version 1.6.0, but feel free to reopen if you encounter it again after you've updated.
