### ISSUE TITLE
Cannot save when VSCode is open on remote machine

### ISSUE THREAD

**Issue by 4s7r0** [SchoofsKelvin/vscode-sshfs#91]
When a copy of VSCode is running on the remote machine with the file in question open, but unmodified, then when you make changes over SSHFS and try and save the changes, it does not work as expected. It does not even error or hang. It does nothing.

To be clear, there are two copies of VSCode running, one local, one remote, both with the same file open. The local copy is connected over SSHFS and makes changes. No changes are made on the remote machine. When I try and save, it does nothing. There is no error shown on either machine. I realize I shouldn't have a copy on the remote machine with the file open, but according to what I know about how these things work, it really shouldn't fail that way. There should be at least a warning, if not several errors thrown.

**Comment by SchoofsKelvin** [comment]
That's a weird setup, and a weirder bug. I'm not entirely sure how restarting the local vscode window solves the issue, unless it's somehow related to SSHD caching/locking some files. Saving a file (ctrl+s) will actually write the file on the remote host, even if no character has been modified. Adding and deleting a character shouldn't make a difference?

**Comment by 4s7r0** [comment]
You are correct. It is a caching issue. I'm closing as it's not your fault.
