### ISSUE TITLE
SSH Forwarding via pageant doesn't work

### ISSUE THREAD

**Issue by AlexeyKondratyev** [SchoofsKelvin/vscode-sshfs#93]
The putty session with the "allow agent forwarding" authenticated parameters does't work.
I'm trying to using a working folder via a bastion host. (pageant<->bastion host<->server )

**Comment by SchoofsKelvin** [comment]
While I don't much knowledge about bastion hosts, it seems to me like a case of SSH hopping #7

As for forwarding the agent, did you set `agentForward` to true in your config? The [ssh2 library](agentForward) I use has an option `agentForward`, and my extension forwards almost all config options (including unknown ones) to it.
