### ISSUE TITLE
How to use in wsl with openSSH agent and ~/.ssh/.config

### ISSUE THREAD

**Issue by ivangretsky** [SchoofsKelvin/vscode-sshfs#97]
Good day! Thanks for the very useful project.

I use Windows 10 wsl and openSSH for ssh connections. I got all my ssh connections defined in `~/.ssh/.config`. Most of them use ssh keys with passphrase. I use ssh-agent to not enter those passphrases.  Is there a way to use wsl ssh-agent and reuse my `~/.ssh/.config`? An example config object would be super useful)

**Comment by SchoofsKelvin** [comment]
I recently added the ability to use Windows' new OpenSSH agent (#83), which might be what you want. I am not sure if Windows has a different agent in WSL, and even if it's the same, if the outer agent can use WSL's `~/.ssh/.config`. #83 shows an example of using Windows' OpenSSH agent.

Does that solve your problem? I'm not entirely sure how well it'll interact with WSL.

**Comment by SchoofsKelvin** [comment]
Closing this issue, as there is now another issue for keeping track of parsing SSH config files (#107)

**Comment by ivangretsky** [comment]
Sorry for a late reply.
As far as I see, WSL uses its own OpenSSH client. I did try to run the Windows OpenSSH client and it does not read WSL ssh config file, at least out of the box. Maybe there is a way to configure that, but I did not find a way to do it yet.

**Comment by ivangretsky** [comment]
@SchoofsKelvin, am I right to assume you do not see any ways and have no intention to investigate the ways of using OpenSSH client installed in WSL Linux? Just to make it clear.
Thanks for you work, by the way!)))

**Comment by SchoofsKelvin** [comment]
> am I right to assume you do not see any ways and have no intention to investigate the ways of using OpenSSH client installed in WSL Linux?

I have actually researched into using `ssh` (both OpenSSH on unix/Windows, as on WSL) and even `plink`, but as far as I'm aware, I can't launch a SSH connection using such a command, then take it over in my extension. Mind that I need access to the whole SSH connection, with channel support. Not just a single terminal.
